// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: TasksManager.proto

// 任务管理器 gRPC 服务定义
// 用于管理任务客户端、服务器节点和任务执行的协议定义文件

package tasksmanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TasksManager_GetTaskClientInfoList_FullMethodName     = "/tasksmanager.TasksManager/GetTaskClientInfoList"
	TasksManager_GetGrpcServerNodeInfoList_FullMethodName = "/tasksmanager.TasksManager/GetGrpcServerNodeInfoList"
	TasksManager_GetTUICConfig_FullMethodName             = "/tasksmanager.TasksManager/GetTUICConfig"
	TasksManager_SubmitTask_FullMethodName                = "/tasksmanager.TasksManager/SubmitTask"
	TasksManager_RegisterClient_FullMethodName            = "/tasksmanager.TasksManager/RegisterClient"
	TasksManager_ClientHeartbeat_FullMethodName           = "/tasksmanager.TasksManager/ClientHeartbeat"
	TasksManager_RegisterNode_FullMethodName              = "/tasksmanager.TasksManager/RegisterNode"
	TasksManager_NodeHeartbeat_FullMethodName             = "/tasksmanager.TasksManager/NodeHeartbeat"
	TasksManager_SendNodeMessage_FullMethodName           = "/tasksmanager.TasksManager/SendNodeMessage"
	TasksManager_SyncNodeList_FullMethodName              = "/tasksmanager.TasksManager/SyncNodeList"
)

// TasksManagerClient is the client API for TasksManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TasksManager 任务管理器 gRPC 服务
// 提供任务客户端管理、服务器节点管理和任务执行等功能
// 支持去中心化架构，每个节点既是服务器也是客户端，可以相互通信
type TasksManagerClient interface {
	// GetTaskClientInfoList 获取任务客户端列表
	// 返回所有已登录并连接到服务器的任务客户端信息列表
	// 包括客户端的基本信息、系统信息、连接状态等
	GetTaskClientInfoList(ctx context.Context, in *TaskClientInfoListRequest, opts ...grpc.CallOption) (*TaskClientInfoListResponse, error)
	// GetGrpcServerNodeInfoList 获取 gRPC 服务器节点列表
	// 返回所有 gRPC 服务器节点的信息列表
	// 包括节点的基本信息、系统信息、运行状态等
	GetGrpcServerNodeInfoList(ctx context.Context, in *GrpcServerNodeInfoListRequest, opts ...grpc.CallOption) (*GrpcServerNodeInfoListResponse, error)
	// GetTUICConfig 获取 TUIC 服务器配置信息
	// 返回 TUIC 服务器的 UUID 和密码，用于客户端自动连接
	// 客户端可以通过此接口获取服务器自动生成的 UUID 和密码，实现无缝连接
	GetTUICConfig(ctx context.Context, in *TUICConfigRequest, opts ...grpc.CallOption) (*TUICConfigResponse, error)
	// SubmitTask 提交任务请求
	// 向指定的任务客户端提交一个新的 HTTP 任务请求
	// 任务将在客户端执行，并返回执行结果（包括响应状态码和响应体）
	SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// RegisterClient 客户端注册
	// 客户端连接到服务器时调用，注册自己的信息
	// 服务器会返回所有已知的服务器节点列表，帮助客户端连接到所有服务器
	RegisterClient(ctx context.Context, in *TaskClientInfo, opts ...grpc.CallOption) (*RegisterClientResponse, error)
	// ClientHeartbeat 客户端心跳
	// 客户端定期发送心跳，告知服务器自己仍然在线
	// 同时更新自己的资源使用情况等信息
	// 服务器会在响应中返回新上线的服务器节点列表（如果有）
	ClientHeartbeat(ctx context.Context, in *TaskClientInfo, opts ...grpc.CallOption) (*ClientHeartbeatResponse, error)
	// RegisterNode 服务器节点注册
	// 新服务器节点加入网络时调用，向其他服务器节点注册自己的信息
	// 接收方节点会返回已知的其他服务器节点列表，帮助新节点快速发现网络中的其他节点
	RegisterNode(ctx context.Context, in *NodeRegistrationRequest, opts ...grpc.CallOption) (*NodeRegistrationResponse, error)
	// NodeHeartbeat 服务器节点心跳
	// 服务器节点定期发送心跳，告知其他服务器节点自己仍然在线
	// 同时可以更新自己的资源使用情况等信息
	// 接收方可能返回其他服务器节点的最新信息
	NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequest, opts ...grpc.CallOption) (*NodeHeartbeatResponse, error)
	// SendNodeMessage 发送节点消息
	// 节点间相互传递消息和指令
	// 支持点对点消息（指定 to_node_uuid）和广播消息（to_node_uuid 为空）
	// 可用于任务分配、状态同步、事件通知等场景
	SendNodeMessage(ctx context.Context, in *NodeMessageRequest, opts ...grpc.CallOption) (*NodeMessageResponse, error)
	// SyncNodeList 同步节点列表
	// 请求与其他节点同步节点列表信息
	// 接收方会比较请求方的已知节点列表，返回需要添加、移除或更新的节点信息
	// 用于维护网络中所有节点的最新状态
	SyncNodeList(ctx context.Context, in *SyncNodeListRequest, opts ...grpc.CallOption) (*SyncNodeListResponse, error)
}

type tasksManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTasksManagerClient(cc grpc.ClientConnInterface) TasksManagerClient {
	return &tasksManagerClient{cc}
}

func (c *tasksManagerClient) GetTaskClientInfoList(ctx context.Context, in *TaskClientInfoListRequest, opts ...grpc.CallOption) (*TaskClientInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskClientInfoListResponse)
	err := c.cc.Invoke(ctx, TasksManager_GetTaskClientInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) GetGrpcServerNodeInfoList(ctx context.Context, in *GrpcServerNodeInfoListRequest, opts ...grpc.CallOption) (*GrpcServerNodeInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrpcServerNodeInfoListResponse)
	err := c.cc.Invoke(ctx, TasksManager_GetGrpcServerNodeInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) GetTUICConfig(ctx context.Context, in *TUICConfigRequest, opts ...grpc.CallOption) (*TUICConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TUICConfigResponse)
	err := c.cc.Invoke(ctx, TasksManager_GetTUICConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TasksManager_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) RegisterClient(ctx context.Context, in *TaskClientInfo, opts ...grpc.CallOption) (*RegisterClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterClientResponse)
	err := c.cc.Invoke(ctx, TasksManager_RegisterClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) ClientHeartbeat(ctx context.Context, in *TaskClientInfo, opts ...grpc.CallOption) (*ClientHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientHeartbeatResponse)
	err := c.cc.Invoke(ctx, TasksManager_ClientHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) RegisterNode(ctx context.Context, in *NodeRegistrationRequest, opts ...grpc.CallOption) (*NodeRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegistrationResponse)
	err := c.cc.Invoke(ctx, TasksManager_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequest, opts ...grpc.CallOption) (*NodeHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeHeartbeatResponse)
	err := c.cc.Invoke(ctx, TasksManager_NodeHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) SendNodeMessage(ctx context.Context, in *NodeMessageRequest, opts ...grpc.CallOption) (*NodeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeMessageResponse)
	err := c.cc.Invoke(ctx, TasksManager_SendNodeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksManagerClient) SyncNodeList(ctx context.Context, in *SyncNodeListRequest, opts ...grpc.CallOption) (*SyncNodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncNodeListResponse)
	err := c.cc.Invoke(ctx, TasksManager_SyncNodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksManagerServer is the server API for TasksManager service.
// All implementations must embed UnimplementedTasksManagerServer
// for forward compatibility.
//
// TasksManager 任务管理器 gRPC 服务
// 提供任务客户端管理、服务器节点管理和任务执行等功能
// 支持去中心化架构，每个节点既是服务器也是客户端，可以相互通信
type TasksManagerServer interface {
	// GetTaskClientInfoList 获取任务客户端列表
	// 返回所有已登录并连接到服务器的任务客户端信息列表
	// 包括客户端的基本信息、系统信息、连接状态等
	GetTaskClientInfoList(context.Context, *TaskClientInfoListRequest) (*TaskClientInfoListResponse, error)
	// GetGrpcServerNodeInfoList 获取 gRPC 服务器节点列表
	// 返回所有 gRPC 服务器节点的信息列表
	// 包括节点的基本信息、系统信息、运行状态等
	GetGrpcServerNodeInfoList(context.Context, *GrpcServerNodeInfoListRequest) (*GrpcServerNodeInfoListResponse, error)
	// GetTUICConfig 获取 TUIC 服务器配置信息
	// 返回 TUIC 服务器的 UUID 和密码，用于客户端自动连接
	// 客户端可以通过此接口获取服务器自动生成的 UUID 和密码，实现无缝连接
	GetTUICConfig(context.Context, *TUICConfigRequest) (*TUICConfigResponse, error)
	// SubmitTask 提交任务请求
	// 向指定的任务客户端提交一个新的 HTTP 任务请求
	// 任务将在客户端执行，并返回执行结果（包括响应状态码和响应体）
	SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// RegisterClient 客户端注册
	// 客户端连接到服务器时调用，注册自己的信息
	// 服务器会返回所有已知的服务器节点列表，帮助客户端连接到所有服务器
	RegisterClient(context.Context, *TaskClientInfo) (*RegisterClientResponse, error)
	// ClientHeartbeat 客户端心跳
	// 客户端定期发送心跳，告知服务器自己仍然在线
	// 同时更新自己的资源使用情况等信息
	// 服务器会在响应中返回新上线的服务器节点列表（如果有）
	ClientHeartbeat(context.Context, *TaskClientInfo) (*ClientHeartbeatResponse, error)
	// RegisterNode 服务器节点注册
	// 新服务器节点加入网络时调用，向其他服务器节点注册自己的信息
	// 接收方节点会返回已知的其他服务器节点列表，帮助新节点快速发现网络中的其他节点
	RegisterNode(context.Context, *NodeRegistrationRequest) (*NodeRegistrationResponse, error)
	// NodeHeartbeat 服务器节点心跳
	// 服务器节点定期发送心跳，告知其他服务器节点自己仍然在线
	// 同时可以更新自己的资源使用情况等信息
	// 接收方可能返回其他服务器节点的最新信息
	NodeHeartbeat(context.Context, *NodeHeartbeatRequest) (*NodeHeartbeatResponse, error)
	// SendNodeMessage 发送节点消息
	// 节点间相互传递消息和指令
	// 支持点对点消息（指定 to_node_uuid）和广播消息（to_node_uuid 为空）
	// 可用于任务分配、状态同步、事件通知等场景
	SendNodeMessage(context.Context, *NodeMessageRequest) (*NodeMessageResponse, error)
	// SyncNodeList 同步节点列表
	// 请求与其他节点同步节点列表信息
	// 接收方会比较请求方的已知节点列表，返回需要添加、移除或更新的节点信息
	// 用于维护网络中所有节点的最新状态
	SyncNodeList(context.Context, *SyncNodeListRequest) (*SyncNodeListResponse, error)
	mustEmbedUnimplementedTasksManagerServer()
}

// UnimplementedTasksManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTasksManagerServer struct{}

func (UnimplementedTasksManagerServer) GetTaskClientInfoList(context.Context, *TaskClientInfoListRequest) (*TaskClientInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskClientInfoList not implemented")
}
func (UnimplementedTasksManagerServer) GetGrpcServerNodeInfoList(context.Context, *GrpcServerNodeInfoListRequest) (*GrpcServerNodeInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrpcServerNodeInfoList not implemented")
}
func (UnimplementedTasksManagerServer) GetTUICConfig(context.Context, *TUICConfigRequest) (*TUICConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTUICConfig not implemented")
}
func (UnimplementedTasksManagerServer) SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedTasksManagerServer) RegisterClient(context.Context, *TaskClientInfo) (*RegisterClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedTasksManagerServer) ClientHeartbeat(context.Context, *TaskClientInfo) (*ClientHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientHeartbeat not implemented")
}
func (UnimplementedTasksManagerServer) RegisterNode(context.Context, *NodeRegistrationRequest) (*NodeRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedTasksManagerServer) NodeHeartbeat(context.Context, *NodeHeartbeatRequest) (*NodeHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeHeartbeat not implemented")
}
func (UnimplementedTasksManagerServer) SendNodeMessage(context.Context, *NodeMessageRequest) (*NodeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNodeMessage not implemented")
}
func (UnimplementedTasksManagerServer) SyncNodeList(context.Context, *SyncNodeListRequest) (*SyncNodeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncNodeList not implemented")
}
func (UnimplementedTasksManagerServer) mustEmbedUnimplementedTasksManagerServer() {}
func (UnimplementedTasksManagerServer) testEmbeddedByValue()                      {}

// UnsafeTasksManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TasksManagerServer will
// result in compilation errors.
type UnsafeTasksManagerServer interface {
	mustEmbedUnimplementedTasksManagerServer()
}

func RegisterTasksManagerServer(s grpc.ServiceRegistrar, srv TasksManagerServer) {
	// If the following call panics, it indicates UnimplementedTasksManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TasksManager_ServiceDesc, srv)
}

func _TasksManager_GetTaskClientInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskClientInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).GetTaskClientInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_GetTaskClientInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).GetTaskClientInfoList(ctx, req.(*TaskClientInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_GetGrpcServerNodeInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcServerNodeInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).GetGrpcServerNodeInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_GetGrpcServerNodeInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).GetGrpcServerNodeInfoList(ctx, req.(*GrpcServerNodeInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_GetTUICConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TUICConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).GetTUICConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_GetTUICConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).GetTUICConfig(ctx, req.(*TUICConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).SubmitTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).RegisterClient(ctx, req.(*TaskClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_ClientHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).ClientHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_ClientHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).ClientHeartbeat(ctx, req.(*TaskClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).RegisterNode(ctx, req.(*NodeRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_NodeHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).NodeHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_NodeHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).NodeHeartbeat(ctx, req.(*NodeHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_SendNodeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).SendNodeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_SendNodeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).SendNodeMessage(ctx, req.(*NodeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksManager_SyncNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncNodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksManagerServer).SyncNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksManager_SyncNodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksManagerServer).SyncNodeList(ctx, req.(*SyncNodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TasksManager_ServiceDesc is the grpc.ServiceDesc for TasksManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TasksManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasksmanager.TasksManager",
	HandlerType: (*TasksManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskClientInfoList",
			Handler:    _TasksManager_GetTaskClientInfoList_Handler,
		},
		{
			MethodName: "GetGrpcServerNodeInfoList",
			Handler:    _TasksManager_GetGrpcServerNodeInfoList_Handler,
		},
		{
			MethodName: "GetTUICConfig",
			Handler:    _TasksManager_GetTUICConfig_Handler,
		},
		{
			MethodName: "SubmitTask",
			Handler:    _TasksManager_SubmitTask_Handler,
		},
		{
			MethodName: "RegisterClient",
			Handler:    _TasksManager_RegisterClient_Handler,
		},
		{
			MethodName: "ClientHeartbeat",
			Handler:    _TasksManager_ClientHeartbeat_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _TasksManager_RegisterNode_Handler,
		},
		{
			MethodName: "NodeHeartbeat",
			Handler:    _TasksManager_NodeHeartbeat_Handler,
		},
		{
			MethodName: "SendNodeMessage",
			Handler:    _TasksManager_SendNodeMessage_Handler,
		},
		{
			MethodName: "SyncNodeList",
			Handler:    _TasksManager_SyncNodeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TasksManager.proto",
}
