// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: TasksManager.proto

// 任务管理器 gRPC 服务定义
// 用于管理任务客户端、服务器节点和任务执行的协议定义文件

package tasksmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskType 任务类型枚举
// 用于表示任务的类型
type TaskType int32

const (
	TaskType_TASK_TYPE_UNKNOWN                             TaskType = 0 // 未知类型 - 任务类型未初始化或无法确定
	TaskType_TASK_TYPE_GOOGLE_EARTH_ROCKTREE_BULK_METADATA TaskType = 1 // 获取RockTree的批量元数据
	TaskType_TASK_TYPE_GOOGLE_EARTH_ROCKTREE_NODE_DATA     TaskType = 2 // 获取RockTree的节点数据
	TaskType_TASK_TYPE_GOOGLE_EARTH_Q2                     TaskType = 3 // 获取Q2数据
	TaskType_TASK_TYPE_GOOGLE_EARTH_IMAGERY                TaskType = 4 // 获取Imagery数据
	TaskType_TASK_TYPE_GOOGLE_EARTH_IMAGERY_HISTORY        TaskType = 5 // 获取Imagery历史数据
	TaskType_TASK_TYPE_GOOGLE_EARTH_QP                     TaskType = 6 // 获取qpQ2数据
	TaskType_TASK_TYPE_GOOGLE_EARTH_TERRAIN                TaskType = 7 // 获取Terrain数据
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNKNOWN",
		1: "TASK_TYPE_GOOGLE_EARTH_ROCKTREE_BULK_METADATA",
		2: "TASK_TYPE_GOOGLE_EARTH_ROCKTREE_NODE_DATA",
		3: "TASK_TYPE_GOOGLE_EARTH_Q2",
		4: "TASK_TYPE_GOOGLE_EARTH_IMAGERY",
		5: "TASK_TYPE_GOOGLE_EARTH_IMAGERY_HISTORY",
		6: "TASK_TYPE_GOOGLE_EARTH_QP",
		7: "TASK_TYPE_GOOGLE_EARTH_TERRAIN",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNKNOWN":                             0,
		"TASK_TYPE_GOOGLE_EARTH_ROCKTREE_BULK_METADATA": 1,
		"TASK_TYPE_GOOGLE_EARTH_ROCKTREE_NODE_DATA":     2,
		"TASK_TYPE_GOOGLE_EARTH_Q2":                     3,
		"TASK_TYPE_GOOGLE_EARTH_IMAGERY":                4,
		"TASK_TYPE_GOOGLE_EARTH_IMAGERY_HISTORY":        5,
		"TASK_TYPE_GOOGLE_EARTH_QP":                     6,
		"TASK_TYPE_GOOGLE_EARTH_TERRAIN":                7,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_TasksManager_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_TasksManager_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{0}
}

// TasksStatus 批量任务执行状态枚举
// 用于表示一组批量任务的整体执行状态（与单个任务的 TaskStatus 不同）
type TasksStatus int32

const (
	TasksStatus_TASKS_STATUS_UNKNOWN TasksStatus = 0 // 未知状态 - 批量任务状态未初始化或无法确定
	TasksStatus_TASKS_STATUS_RUNNING TasksStatus = 1 // 运行中 - 批量任务正在执行
	TasksStatus_TASKS_STATUS_PAUSED  TasksStatus = 2 // 已暂停 - 批量任务已暂停，可以恢复
	TasksStatus_TASKS_STATUS_STOPPED TasksStatus = 3 // 已停止 - 批量任务已停止，需要重新启动
)

// Enum value maps for TasksStatus.
var (
	TasksStatus_name = map[int32]string{
		0: "TASKS_STATUS_UNKNOWN",
		1: "TASKS_STATUS_RUNNING",
		2: "TASKS_STATUS_PAUSED",
		3: "TASKS_STATUS_STOPPED",
	}
	TasksStatus_value = map[string]int32{
		"TASKS_STATUS_UNKNOWN": 0,
		"TASKS_STATUS_RUNNING": 1,
		"TASKS_STATUS_PAUSED":  2,
		"TASKS_STATUS_STOPPED": 3,
	}
)

func (x TasksStatus) Enum() *TasksStatus {
	p := new(TasksStatus)
	*p = x
	return p
}

func (x TasksStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TasksStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_TasksManager_proto_enumTypes[1].Descriptor()
}

func (TasksStatus) Type() protoreflect.EnumType {
	return &file_TasksManager_proto_enumTypes[1]
}

func (x TasksStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TasksStatus.Descriptor instead.
func (TasksStatus) EnumDescriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{1}
}

// TaskStatus 单个任务执行状态枚举
// 用于表示单个任务的生命周期状态（与批量任务的 TasksStatus 不同）
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_PENDING TaskStatus = 0 // 等待中 - 任务已创建，等待执行
	TaskStatus_TASK_STATUS_RUNNING TaskStatus = 1 // 运行中 - 任务正在执行
	TaskStatus_TASK_STATUS_SUCCESS TaskStatus = 2 // 成功 - 任务执行成功完成
	TaskStatus_TASK_STATUS_FAILED  TaskStatus = 3 // 失败 - 任务执行失败
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_PENDING",
		1: "TASK_STATUS_RUNNING",
		2: "TASK_STATUS_SUCCESS",
		3: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_PENDING": 0,
		"TASK_STATUS_RUNNING": 1,
		"TASK_STATUS_SUCCESS": 2,
		"TASK_STATUS_FAILED":  3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_TasksManager_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_TasksManager_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{2}
}

// ClientTaskStatus 任务客户端连接状态枚举
// 用于表示任务客户端与服务器的连接状态和在线状态
type ClientTaskStatus int32

const (
	ClientTaskStatus_CLIENT_TASK_STATUS_OFFLINE       ClientTaskStatus = 0 // 离线 - 客户端未连接或连接已断开
	ClientTaskStatus_CLIENT_TASK_STATUS_ONLINE        ClientTaskStatus = 1 // 在线 - 客户端正常连接，可以接收任务
	ClientTaskStatus_CLIENT_TASK_STATUS_AWAY          ClientTaskStatus = 2 // 暂离 - 客户端在线但暂时不可用（如休眠模式）
	ClientTaskStatus_CLIENT_TASK_STATUS_CONNECTING    ClientTaskStatus = 3 // 连接中 - 客户端正在建立连接
	ClientTaskStatus_CLIENT_TASK_STATUS_DISCONNECTING ClientTaskStatus = 4 // 断开中 - 客户端正在关闭连接
)

// Enum value maps for ClientTaskStatus.
var (
	ClientTaskStatus_name = map[int32]string{
		0: "CLIENT_TASK_STATUS_OFFLINE",
		1: "CLIENT_TASK_STATUS_ONLINE",
		2: "CLIENT_TASK_STATUS_AWAY",
		3: "CLIENT_TASK_STATUS_CONNECTING",
		4: "CLIENT_TASK_STATUS_DISCONNECTING",
	}
	ClientTaskStatus_value = map[string]int32{
		"CLIENT_TASK_STATUS_OFFLINE":       0,
		"CLIENT_TASK_STATUS_ONLINE":        1,
		"CLIENT_TASK_STATUS_AWAY":          2,
		"CLIENT_TASK_STATUS_CONNECTING":    3,
		"CLIENT_TASK_STATUS_DISCONNECTING": 4,
	}
)

func (x ClientTaskStatus) Enum() *ClientTaskStatus {
	p := new(ClientTaskStatus)
	*p = x
	return p
}

func (x ClientTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_TasksManager_proto_enumTypes[3].Descriptor()
}

func (ClientTaskStatus) Type() protoreflect.EnumType {
	return &file_TasksManager_proto_enumTypes[3]
}

func (x ClientTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTaskStatus.Descriptor instead.
func (ClientTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{3}
}

// TaskMethod HTTP 请求方法枚举
// 对应标准 HTTP 方法，用于指定任务请求使用的 HTTP 动作
type TaskMethod int32

const (
	TaskMethod_TASK_METHOD_GET     TaskMethod = 0 // GET - 获取资源
	TaskMethod_TASK_METHOD_POST    TaskMethod = 1 // POST - 提交数据
	TaskMethod_TASK_METHOD_PUT     TaskMethod = 2 // PUT - 更新资源（完整替换）
	TaskMethod_TASK_METHOD_DELETE  TaskMethod = 3 // DELETE - 删除资源
	TaskMethod_TASK_METHOD_PATCH   TaskMethod = 4 // PATCH - 部分更新资源
	TaskMethod_TASK_METHOD_HEAD    TaskMethod = 5 // HEAD - 获取响应头（无响应体）
	TaskMethod_TASK_METHOD_OPTIONS TaskMethod = 6 // OPTIONS - 获取服务器支持的 HTTP 方法
)

// Enum value maps for TaskMethod.
var (
	TaskMethod_name = map[int32]string{
		0: "TASK_METHOD_GET",
		1: "TASK_METHOD_POST",
		2: "TASK_METHOD_PUT",
		3: "TASK_METHOD_DELETE",
		4: "TASK_METHOD_PATCH",
		5: "TASK_METHOD_HEAD",
		6: "TASK_METHOD_OPTIONS",
	}
	TaskMethod_value = map[string]int32{
		"TASK_METHOD_GET":     0,
		"TASK_METHOD_POST":    1,
		"TASK_METHOD_PUT":     2,
		"TASK_METHOD_DELETE":  3,
		"TASK_METHOD_PATCH":   4,
		"TASK_METHOD_HEAD":    5,
		"TASK_METHOD_OPTIONS": 6,
	}
)

func (x TaskMethod) Enum() *TaskMethod {
	p := new(TaskMethod)
	*p = x
	return p
}

func (x TaskMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_TasksManager_proto_enumTypes[4].Descriptor()
}

func (TaskMethod) Type() protoreflect.EnumType {
	return &file_TasksManager_proto_enumTypes[4]
}

func (x TaskMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskMethod.Descriptor instead.
func (TaskMethod) EnumDescriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{4}
}

// TaskClientInfo 任务客户端信息
// 客户端与 gRPC 服务器连接时需要提供的信息，用于标识和跟踪客户端状态
// 包含客户端的静态配置信息和实时资源使用情况
type TaskClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基本信息字段
	ClientUuid           string           `protobuf:"bytes,1,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`                                                          // 客户端唯一标识符（UUID）
	ClientName           string           `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`                                                          // 客户端名称/显示名称
	ClientIp             string           `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                                                                // 客户端 IP 地址
	ClientSystem         string           `protobuf:"bytes,4,opt,name=client_system,json=clientSystem,proto3" json:"client_system,omitempty"`                                                    // 客户端操作系统信息（如 "Linux", "Windows"）
	ClientVersion        string           `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`                                                 // 客户端版本号
	ClientCpu            string           `protobuf:"bytes,6,opt,name=client_cpu,json=clientCpu,proto3" json:"client_cpu,omitempty"`                                                             // 客户端 CPU 信息（型号、核心数等，静态信息）
	ClientMemory         string           `protobuf:"bytes,7,opt,name=client_memory,json=clientMemory,proto3" json:"client_memory,omitempty"`                                                    // 客户端内存信息（总内存大小等，静态信息）
	ClientCreateTime     string           `protobuf:"bytes,8,opt,name=client_create_time,json=clientCreateTime,proto3" json:"client_create_time,omitempty"`                                      // 客户端创建时间（ISO 8601 格式字符串）
	ClientLastActiveTime string           `protobuf:"bytes,9,opt,name=client_last_active_time,json=clientLastActiveTime,proto3" json:"client_last_active_time,omitempty"`                        // 客户端最后活跃时间（ISO 8601 格式字符串）
	ClientTaskStatus     ClientTaskStatus `protobuf:"varint,10,opt,name=client_task_status,json=clientTaskStatus,proto3,enum=tasksmanager.ClientTaskStatus" json:"client_task_status,omitempty"` // 客户端连接状态（在线/离线等）
	// 实时资源使用情况字段（动态变化数据）
	// 客户端需要实时传递这些数据，让节点服务了解客户端的健康状况
	CpuUsagePercent      *float64 `protobuf:"fixed64,11,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3,oneof" json:"cpu_usage_percent,omitempty"`                    // CPU 使用率（百分比，0-100）
	MemoryUsedBytes      *int64   `protobuf:"varint,12,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3,oneof" json:"memory_used_bytes,omitempty"`                     // 内存已使用量（字节）
	MemoryTotalBytes     *int64   `protobuf:"varint,13,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3,oneof" json:"memory_total_bytes,omitempty"`                  // 内存总容量（字节）
	NetworkRxBytesPerSec *float64 `protobuf:"fixed64,14,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3,oneof" json:"network_rx_bytes_per_sec,omitempty"` // 网络接收带宽（字节/秒，下载速度）
	NetworkTxBytesPerSec *float64 `protobuf:"fixed64,15,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3,oneof" json:"network_tx_bytes_per_sec,omitempty"` // 网络发送带宽（字节/秒，上传速度）
	DiskUsedBytes        *int64   `protobuf:"varint,16,opt,name=disk_used_bytes,json=diskUsedBytes,proto3,oneof" json:"disk_used_bytes,omitempty"`                           // 硬盘已使用空间（字节）
	DiskTotalBytes       *int64   `protobuf:"varint,17,opt,name=disk_total_bytes,json=diskTotalBytes,proto3,oneof" json:"disk_total_bytes,omitempty"`                        // 硬盘总容量（字节）
	ResourceUpdateTime   *string  `protobuf:"bytes,18,opt,name=resource_update_time,json=resourceUpdateTime,proto3,oneof" json:"resource_update_time,omitempty"`             // 资源数据更新时间（ISO 8601 格式字符串）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskClientInfo) Reset() {
	*x = TaskClientInfo{}
	mi := &file_TasksManager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClientInfo) ProtoMessage() {}

func (x *TaskClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClientInfo.ProtoReflect.Descriptor instead.
func (*TaskClientInfo) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{0}
}

func (x *TaskClientInfo) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

func (x *TaskClientInfo) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *TaskClientInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *TaskClientInfo) GetClientSystem() string {
	if x != nil {
		return x.ClientSystem
	}
	return ""
}

func (x *TaskClientInfo) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *TaskClientInfo) GetClientCpu() string {
	if x != nil {
		return x.ClientCpu
	}
	return ""
}

func (x *TaskClientInfo) GetClientMemory() string {
	if x != nil {
		return x.ClientMemory
	}
	return ""
}

func (x *TaskClientInfo) GetClientCreateTime() string {
	if x != nil {
		return x.ClientCreateTime
	}
	return ""
}

func (x *TaskClientInfo) GetClientLastActiveTime() string {
	if x != nil {
		return x.ClientLastActiveTime
	}
	return ""
}

func (x *TaskClientInfo) GetClientTaskStatus() ClientTaskStatus {
	if x != nil {
		return x.ClientTaskStatus
	}
	return ClientTaskStatus_CLIENT_TASK_STATUS_OFFLINE
}

func (x *TaskClientInfo) GetCpuUsagePercent() float64 {
	if x != nil && x.CpuUsagePercent != nil {
		return *x.CpuUsagePercent
	}
	return 0
}

func (x *TaskClientInfo) GetMemoryUsedBytes() int64 {
	if x != nil && x.MemoryUsedBytes != nil {
		return *x.MemoryUsedBytes
	}
	return 0
}

func (x *TaskClientInfo) GetMemoryTotalBytes() int64 {
	if x != nil && x.MemoryTotalBytes != nil {
		return *x.MemoryTotalBytes
	}
	return 0
}

func (x *TaskClientInfo) GetNetworkRxBytesPerSec() float64 {
	if x != nil && x.NetworkRxBytesPerSec != nil {
		return *x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *TaskClientInfo) GetNetworkTxBytesPerSec() float64 {
	if x != nil && x.NetworkTxBytesPerSec != nil {
		return *x.NetworkTxBytesPerSec
	}
	return 0
}

func (x *TaskClientInfo) GetDiskUsedBytes() int64 {
	if x != nil && x.DiskUsedBytes != nil {
		return *x.DiskUsedBytes
	}
	return 0
}

func (x *TaskClientInfo) GetDiskTotalBytes() int64 {
	if x != nil && x.DiskTotalBytes != nil {
		return *x.DiskTotalBytes
	}
	return 0
}

func (x *TaskClientInfo) GetResourceUpdateTime() string {
	if x != nil && x.ResourceUpdateTime != nil {
		return *x.ResourceUpdateTime
	}
	return ""
}

// TaskClientInfoListRequest 任务客户端列表请求
// 获取已登录的用户（客户端）列表的请求消息
type TaskClientInfoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskClientInfoListRequest) Reset() {
	*x = TaskClientInfoListRequest{}
	mi := &file_TasksManager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskClientInfoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClientInfoListRequest) ProtoMessage() {}

func (x *TaskClientInfoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClientInfoListRequest.ProtoReflect.Descriptor instead.
func (*TaskClientInfoListRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{1}
}

// TaskClientInfoListResponse 任务客户端列表响应
// 返回已登录的用户（客户端）列表
type TaskClientInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TaskClientInfo      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 已登录的客户端信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskClientInfoListResponse) Reset() {
	*x = TaskClientInfoListResponse{}
	mi := &file_TasksManager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskClientInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClientInfoListResponse) ProtoMessage() {}

func (x *TaskClientInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClientInfoListResponse.ProtoReflect.Descriptor instead.
func (*TaskClientInfoListResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{2}
}

func (x *TaskClientInfoListResponse) GetItems() []*TaskClientInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// RegisterClientResponse 客户端注册响应
// 客户端注册请求的响应，返回注册结果和已知的服务器节点列表
type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                           // 注册是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                            // 响应消息
	ServerNodes   []*GrpcServerNodeInfo  `protobuf:"bytes,3,rep,name=server_nodes,json=serverNodes,proto3" json:"server_nodes,omitempty"` // 所有已知的服务器节点列表（用于客户端连接）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_TasksManager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterClientResponse) GetServerNodes() []*GrpcServerNodeInfo {
	if x != nil {
		return x.ServerNodes
	}
	return nil
}

// ClientHeartbeatResponse 客户端心跳响应
// 客户端心跳请求的响应，可能包含新上线的服务器节点信息
type ClientHeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                      // 心跳是否成功
	NewServerNodes []*GrpcServerNodeInfo  `protobuf:"bytes,2,rep,name=new_server_nodes,json=newServerNodes,proto3" json:"new_server_nodes,omitempty"` // 新上线的服务器节点列表（如果有）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientHeartbeatResponse) Reset() {
	*x = ClientHeartbeatResponse{}
	mi := &file_TasksManager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartbeatResponse) ProtoMessage() {}

func (x *ClientHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ClientHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{4}
}

func (x *ClientHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientHeartbeatResponse) GetNewServerNodes() []*GrpcServerNodeInfo {
	if x != nil {
		return x.NewServerNodes
	}
	return nil
}

// GrpcServerNodeInfo gRPC 服务器节点信息
// 用于标识和跟踪 gRPC 服务器节点的状态和配置信息
// 包含节点的静态配置信息和实时资源使用情况
type GrpcServerNodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基本信息字段
	NodeUuid           string `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`                                    // 节点唯一标识符（UUID）
	NodeName           string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                                    // 节点名称/显示名称
	NodeIp             string `protobuf:"bytes,3,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`                                          // 节点 IP 地址
	NodePort           string `protobuf:"bytes,4,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`                                    // 节点服务端口号
	NodeSystem         string `protobuf:"bytes,5,opt,name=node_system,json=nodeSystem,proto3" json:"node_system,omitempty"`                              // 节点操作系统信息（如 "Linux", "Windows"）
	NodeVersion        string `protobuf:"bytes,6,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`                           // 节点版本号
	NodeCpu            string `protobuf:"bytes,7,opt,name=node_cpu,json=nodeCpu,proto3" json:"node_cpu,omitempty"`                                       // 节点 CPU 信息（型号、核心数等，静态信息）
	NodeMemory         string `protobuf:"bytes,8,opt,name=node_memory,json=nodeMemory,proto3" json:"node_memory,omitempty"`                              // 节点内存信息（总内存大小等，静态信息）
	NodeCreateTime     string `protobuf:"bytes,9,opt,name=node_create_time,json=nodeCreateTime,proto3" json:"node_create_time,omitempty"`                // 节点创建时间（ISO 8601 格式字符串）
	NodeLastActiveTime string `protobuf:"bytes,10,opt,name=node_last_active_time,json=nodeLastActiveTime,proto3" json:"node_last_active_time,omitempty"` // 节点最后活跃时间（ISO 8601 格式字符串）
	// 实时资源使用情况字段（动态变化数据）
	CpuUsagePercent      *float64 `protobuf:"fixed64,11,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3,oneof" json:"cpu_usage_percent,omitempty"`                    // CPU 使用率（百分比，0-100）
	MemoryUsedBytes      *int64   `protobuf:"varint,12,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3,oneof" json:"memory_used_bytes,omitempty"`                     // 内存已使用量（字节）
	MemoryTotalBytes     *int64   `protobuf:"varint,13,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3,oneof" json:"memory_total_bytes,omitempty"`                  // 内存总容量（字节）
	NetworkRxBytesPerSec *float64 `protobuf:"fixed64,14,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3,oneof" json:"network_rx_bytes_per_sec,omitempty"` // 网络接收带宽（字节/秒，下行速度）
	NetworkTxBytesPerSec *float64 `protobuf:"fixed64,15,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3,oneof" json:"network_tx_bytes_per_sec,omitempty"` // 网络发送带宽（字节/秒，上行速度）
	DiskUsedBytes        *int64   `protobuf:"varint,16,opt,name=disk_used_bytes,json=diskUsedBytes,proto3,oneof" json:"disk_used_bytes,omitempty"`                           // 硬盘已使用空间（字节）
	DiskTotalBytes       *int64   `protobuf:"varint,17,opt,name=disk_total_bytes,json=diskTotalBytes,proto3,oneof" json:"disk_total_bytes,omitempty"`                        // 硬盘总容量（字节）
	ResourceUpdateTime   *string  `protobuf:"bytes,18,opt,name=resource_update_time,json=resourceUpdateTime,proto3,oneof" json:"resource_update_time,omitempty"`             // 资源数据更新时间（ISO 8601 格式字符串）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GrpcServerNodeInfo) Reset() {
	*x = GrpcServerNodeInfo{}
	mi := &file_TasksManager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcServerNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcServerNodeInfo) ProtoMessage() {}

func (x *GrpcServerNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcServerNodeInfo.ProtoReflect.Descriptor instead.
func (*GrpcServerNodeInfo) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcServerNodeInfo) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodePort() string {
	if x != nil {
		return x.NodePort
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeSystem() string {
	if x != nil {
		return x.NodeSystem
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeCpu() string {
	if x != nil {
		return x.NodeCpu
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeMemory() string {
	if x != nil {
		return x.NodeMemory
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeCreateTime() string {
	if x != nil {
		return x.NodeCreateTime
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetNodeLastActiveTime() string {
	if x != nil {
		return x.NodeLastActiveTime
	}
	return ""
}

func (x *GrpcServerNodeInfo) GetCpuUsagePercent() float64 {
	if x != nil && x.CpuUsagePercent != nil {
		return *x.CpuUsagePercent
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetMemoryUsedBytes() int64 {
	if x != nil && x.MemoryUsedBytes != nil {
		return *x.MemoryUsedBytes
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetMemoryTotalBytes() int64 {
	if x != nil && x.MemoryTotalBytes != nil {
		return *x.MemoryTotalBytes
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetNetworkRxBytesPerSec() float64 {
	if x != nil && x.NetworkRxBytesPerSec != nil {
		return *x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetNetworkTxBytesPerSec() float64 {
	if x != nil && x.NetworkTxBytesPerSec != nil {
		return *x.NetworkTxBytesPerSec
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetDiskUsedBytes() int64 {
	if x != nil && x.DiskUsedBytes != nil {
		return *x.DiskUsedBytes
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetDiskTotalBytes() int64 {
	if x != nil && x.DiskTotalBytes != nil {
		return *x.DiskTotalBytes
	}
	return 0
}

func (x *GrpcServerNodeInfo) GetResourceUpdateTime() string {
	if x != nil && x.ResourceUpdateTime != nil {
		return *x.ResourceUpdateTime
	}
	return ""
}

// GrpcServerNodeInfoListRequest gRPC 服务器节点列表请求
// 获取 gRPC 服务器节点列表的请求消息
type GrpcServerNodeInfoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcServerNodeInfoListRequest) Reset() {
	*x = GrpcServerNodeInfoListRequest{}
	mi := &file_TasksManager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcServerNodeInfoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcServerNodeInfoListRequest) ProtoMessage() {}

func (x *GrpcServerNodeInfoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcServerNodeInfoListRequest.ProtoReflect.Descriptor instead.
func (*GrpcServerNodeInfoListRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{6}
}

// GrpcServerNodeInfoListResponse gRPC 服务器节点列表响应
// 返回 gRPC 服务器节点列表
type GrpcServerNodeInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GrpcServerNodeInfo  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 服务器节点信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcServerNodeInfoListResponse) Reset() {
	*x = GrpcServerNodeInfoListResponse{}
	mi := &file_TasksManager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcServerNodeInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcServerNodeInfoListResponse) ProtoMessage() {}

func (x *GrpcServerNodeInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcServerNodeInfoListResponse.ProtoReflect.Descriptor instead.
func (*GrpcServerNodeInfoListResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcServerNodeInfoListResponse) GetItems() []*GrpcServerNodeInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// NodeRegistrationRequest 节点注册请求
// 新节点加入网络时，向其他节点注册自己的信息
type NodeRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *GrpcServerNodeInfo    `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`       // 节点信息
	KnownNodes    []string               `protobuf:"bytes,2,rep,name=known_nodes,json=knownNodes,proto3" json:"known_nodes,omitempty"` // 已知的其他节点地址列表（用于网络发现）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistrationRequest) Reset() {
	*x = NodeRegistrationRequest{}
	mi := &file_TasksManager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationRequest) ProtoMessage() {}

func (x *NodeRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationRequest.ProtoReflect.Descriptor instead.
func (*NodeRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{8}
}

func (x *NodeRegistrationRequest) GetNodeInfo() *GrpcServerNodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeRegistrationRequest) GetKnownNodes() []string {
	if x != nil {
		return x.KnownNodes
	}
	return nil
}

// NodeRegistrationResponse 节点注册响应
// 返回注册结果和已知节点列表
type NodeRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 注册是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	KnownNodes    []*GrpcServerNodeInfo  `protobuf:"bytes,3,rep,name=known_nodes,json=knownNodes,proto3" json:"known_nodes,omitempty"` // 已知的其他节点列表（用于网络发现）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistrationResponse) Reset() {
	*x = NodeRegistrationResponse{}
	mi := &file_TasksManager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationResponse) ProtoMessage() {}

func (x *NodeRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationResponse.ProtoReflect.Descriptor instead.
func (*NodeRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{9}
}

func (x *NodeRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeRegistrationResponse) GetKnownNodes() []*GrpcServerNodeInfo {
	if x != nil {
		return x.KnownNodes
	}
	return nil
}

// NodeHeartbeatRequest 节点心跳请求
// 节点定期发送心跳，告知其他节点自己仍然在线
type NodeHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUuid      string                 `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"` // 节点 UUID
	NodeInfo      *GrpcServerNodeInfo    `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"` // 当前节点信息（包含最新的资源使用情况）
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 心跳时间戳（Unix 时间戳，毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHeartbeatRequest) Reset() {
	*x = NodeHeartbeatRequest{}
	mi := &file_TasksManager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeatRequest) ProtoMessage() {}

func (x *NodeHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*NodeHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{10}
}

func (x *NodeHeartbeatRequest) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *NodeHeartbeatRequest) GetNodeInfo() *GrpcServerNodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// NodeHeartbeatResponse 节点心跳响应
// 响应心跳请求，可能包含其他节点的最新信息
type NodeHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // 心跳是否成功
	UpdatedNodes  []*GrpcServerNodeInfo  `protobuf:"bytes,2,rep,name=updated_nodes,json=updatedNodes,proto3" json:"updated_nodes,omitempty"` // 其他节点的最新信息（如有更新）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHeartbeatResponse) Reset() {
	*x = NodeHeartbeatResponse{}
	mi := &file_TasksManager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeatResponse) ProtoMessage() {}

func (x *NodeHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*NodeHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{11}
}

func (x *NodeHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeHeartbeatResponse) GetUpdatedNodes() []*GrpcServerNodeInfo {
	if x != nil {
		return x.UpdatedNodes
	}
	return nil
}

// NodeMessage 节点间消息
// 用于节点间相互传递信息和指令
type NodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`            // 消息唯一标识符
	FromNodeUuid  string                 `protobuf:"bytes,2,opt,name=from_node_uuid,json=fromNodeUuid,proto3" json:"from_node_uuid,omitempty"` // 发送方节点 UUID
	ToNodeUuid    string                 `protobuf:"bytes,3,opt,name=to_node_uuid,json=toNodeUuid,proto3" json:"to_node_uuid,omitempty"`       // 接收方节点 UUID（空字符串表示广播）
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`      // 消息类型（如 "TASK_REQUEST", "TASK_RESULT", "SYNC_REQUEST" 等）
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                                 // 消息负载（JSON 或其他格式的数据）
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // 消息时间戳（Unix 时间戳，毫秒）
	Ttl           *int32                 `protobuf:"varint,7,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`                                  // 消息生存时间（跳数，用于限制广播范围）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_TasksManager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{12}
}

func (x *NodeMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NodeMessage) GetFromNodeUuid() string {
	if x != nil {
		return x.FromNodeUuid
	}
	return ""
}

func (x *NodeMessage) GetToNodeUuid() string {
	if x != nil {
		return x.ToNodeUuid
	}
	return ""
}

func (x *NodeMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *NodeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NodeMessage) GetTtl() int32 {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return 0
}

// NodeMessageRequest 节点消息发送请求
// 向其他节点发送消息
type NodeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *NodeMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 要发送的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessageRequest) Reset() {
	*x = NodeMessageRequest{}
	mi := &file_TasksManager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessageRequest) ProtoMessage() {}

func (x *NodeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessageRequest.ProtoReflect.Descriptor instead.
func (*NodeMessageRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{13}
}

func (x *NodeMessageRequest) GetMessage() *NodeMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// NodeMessageResponse 节点消息响应
// 消息发送结果
type NodeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功发送
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessageResponse) Reset() {
	*x = NodeMessageResponse{}
	mi := &file_TasksManager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessageResponse) ProtoMessage() {}

func (x *NodeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessageResponse.ProtoReflect.Descriptor instead.
func (*NodeMessageResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{14}
}

func (x *NodeMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SyncNodeListRequest 同步节点列表请求
// 请求与其他节点同步节点列表
type SyncNodeListRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeUuid string                 `protobuf:"bytes,1,opt,name=requesting_node_uuid,json=requestingNodeUuid,proto3" json:"requesting_node_uuid,omitempty"` // 请求方节点 UUID
	KnownNodeUuids     []string               `protobuf:"bytes,2,rep,name=known_node_uuids,json=knownNodeUuids,proto3" json:"known_node_uuids,omitempty"`             // 当前已知的节点 UUID 列表
	LastSyncTime       int64                  `protobuf:"varint,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`                  // 上次同步时间（Unix 时间戳，毫秒）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncNodeListRequest) Reset() {
	*x = SyncNodeListRequest{}
	mi := &file_TasksManager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNodeListRequest) ProtoMessage() {}

func (x *SyncNodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNodeListRequest.ProtoReflect.Descriptor instead.
func (*SyncNodeListRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{15}
}

func (x *SyncNodeListRequest) GetRequestingNodeUuid() string {
	if x != nil {
		return x.RequestingNodeUuid
	}
	return ""
}

func (x *SyncNodeListRequest) GetKnownNodeUuids() []string {
	if x != nil {
		return x.KnownNodeUuids
	}
	return nil
}

func (x *SyncNodeListRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

// SyncNodeListResponse 同步节点列表响应
// 返回需要同步的节点信息
type SyncNodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodesToAdd    []*GrpcServerNodeInfo  `protobuf:"bytes,1,rep,name=nodes_to_add,json=nodesToAdd,proto3" json:"nodes_to_add,omitempty"`          // 需要添加的新节点
	NodesToRemove []string               `protobuf:"bytes,2,rep,name=nodes_to_remove,json=nodesToRemove,proto3" json:"nodes_to_remove,omitempty"` // 需要移除的节点 UUID（已离线）
	NodesToUpdate []*GrpcServerNodeInfo  `protobuf:"bytes,3,rep,name=nodes_to_update,json=nodesToUpdate,proto3" json:"nodes_to_update,omitempty"` // 需要更新的节点信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncNodeListResponse) Reset() {
	*x = SyncNodeListResponse{}
	mi := &file_TasksManager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNodeListResponse) ProtoMessage() {}

func (x *SyncNodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNodeListResponse.ProtoReflect.Descriptor instead.
func (*SyncNodeListResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{16}
}

func (x *SyncNodeListResponse) GetNodesToAdd() []*GrpcServerNodeInfo {
	if x != nil {
		return x.NodesToAdd
	}
	return nil
}

func (x *SyncNodeListResponse) GetNodesToRemove() []string {
	if x != nil {
		return x.NodesToRemove
	}
	return nil
}

func (x *SyncNodeListResponse) GetNodesToUpdate() []*GrpcServerNodeInfo {
	if x != nil {
		return x.NodesToUpdate
	}
	return nil
}

// TaskRequest 任务请求消息
// 用于提交新的任务请求，包含任务执行所需的所有信息
// 相比最初的设计，这里将原来的 URI 拆分为瓦片键和时间版本等字段
type TaskRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskClientId string                 `protobuf:"bytes,1,opt,name=task_client_id,json=taskClientId,proto3" json:"task_client_id,omitempty"`               // 任务客户端标识符，指定执行任务的客户端
	TaskType     TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=tasksmanager.TaskType" json:"task_type,omitempty"` // 任务类型
	// 针对 Google Earth / RockTree 等任务的关键定位字段
	TileKey      string `protobuf:"bytes,3,opt,name=TileKey,proto3" json:"TileKey,omitempty"`                  // 瓦片键（如 QK 编码）
	Epoch        int32  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`                     // 主版本号（Epoch）
	ImageryEpoch *int32 `protobuf:"varint,5,opt,name=imageryEpoch,proto3,oneof" json:"imageryEpoch,omitempty"` // 影像版本号（可选）
	// 通用 HTTP 相关字段
	TaskBody      []byte      `protobuf:"bytes,6,opt,name=task_body,json=taskBody,proto3,oneof" json:"task_body,omitempty"`                                     // 任务请求体，HTTP 请求的 body 内容（如 POST 请求的数据）
	TaskMethod    *TaskMethod `protobuf:"varint,7,opt,name=task_method,json=taskMethod,proto3,enum=tasksmanager.TaskMethod,oneof" json:"task_method,omitempty"` // HTTP 请求方法（GET、POST、PUT、DELETE 等）
	TaskStatus    *TaskStatus `protobuf:"varint,8,opt,name=task_status,json=taskStatus,proto3,enum=tasksmanager.TaskStatus,oneof" json:"task_status,omitempty"` // 任务初始状态（通常为 PENDING）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_TasksManager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{17}
}

func (x *TaskRequest) GetTaskClientId() string {
	if x != nil {
		return x.TaskClientId
	}
	return ""
}

func (x *TaskRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNKNOWN
}

func (x *TaskRequest) GetTileKey() string {
	if x != nil {
		return x.TileKey
	}
	return ""
}

func (x *TaskRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskRequest) GetImageryEpoch() int32 {
	if x != nil && x.ImageryEpoch != nil {
		return *x.ImageryEpoch
	}
	return 0
}

func (x *TaskRequest) GetTaskBody() []byte {
	if x != nil {
		return x.TaskBody
	}
	return nil
}

func (x *TaskRequest) GetTaskMethod() TaskMethod {
	if x != nil && x.TaskMethod != nil {
		return *x.TaskMethod
	}
	return TaskMethod_TASK_METHOD_GET
}

func (x *TaskRequest) GetTaskStatus() TaskStatus {
	if x != nil && x.TaskStatus != nil {
		return *x.TaskStatus
	}
	return TaskStatus_TASK_STATUS_PENDING
}

// TaskResponse 任务响应消息
// 任务执行完成后返回的响应结果
// 保持与 TaskRequest 对应的瓦片键和版本信息，便于结果归属
type TaskResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskClientId string                 `protobuf:"bytes,1,opt,name=task_client_id,json=taskClientId,proto3" json:"task_client_id,omitempty"`               // 任务客户端标识符，与请求中的对应
	TaskType     TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=tasksmanager.TaskType" json:"task_type,omitempty"` // 任务类型
	// 与请求对应的关键定位字段
	TileKey      string `protobuf:"bytes,3,opt,name=TileKey,proto3" json:"TileKey,omitempty"`                  // 瓦片键
	Epoch        int32  `protobuf:"varint,4,opt,name=Epoch,proto3" json:"Epoch,omitempty"`                     // 主版本号（Epoch）
	ImageryEpoch *int32 `protobuf:"varint,5,opt,name=imageryEpoch,proto3,oneof" json:"imageryEpoch,omitempty"` // 影像版本号（可选）
	// HTTP 结果
	TaskResponseBody       []byte `protobuf:"bytes,6,opt,name=task_response_body,json=taskResponseBody,proto3,oneof" json:"task_response_body,omitempty"`                      // HTTP 响应体内容（可选，任务失败时可能为空）
	TaskResponseStatusCode *int32 `protobuf:"varint,7,opt,name=task_response_status_code,json=taskResponseStatusCode,proto3,oneof" json:"task_response_status_code,omitempty"` // HTTP 响应状态码（可选，如 200、404、500 等）
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_TasksManager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TasksManager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_TasksManager_proto_rawDescGZIP(), []int{18}
}

func (x *TaskResponse) GetTaskClientId() string {
	if x != nil {
		return x.TaskClientId
	}
	return ""
}

func (x *TaskResponse) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNKNOWN
}

func (x *TaskResponse) GetTileKey() string {
	if x != nil {
		return x.TileKey
	}
	return ""
}

func (x *TaskResponse) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskResponse) GetImageryEpoch() int32 {
	if x != nil && x.ImageryEpoch != nil {
		return *x.ImageryEpoch
	}
	return 0
}

func (x *TaskResponse) GetTaskResponseBody() []byte {
	if x != nil {
		return x.TaskResponseBody
	}
	return nil
}

func (x *TaskResponse) GetTaskResponseStatusCode() int32 {
	if x != nil && x.TaskResponseStatusCode != nil {
		return *x.TaskResponseStatusCode
	}
	return 0
}

var File_TasksManager_proto protoreflect.FileDescriptor

const file_TasksManager_proto_rawDesc = "" +
	"\n" +
	"\x12TasksManager.proto\x12\ftasksmanager\"\x93\b\n" +
	"\x0eTaskClientInfo\x12\x1f\n" +
	"\vclient_uuid\x18\x01 \x01(\tR\n" +
	"clientUuid\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12#\n" +
	"\rclient_system\x18\x04 \x01(\tR\fclientSystem\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\x12\x1d\n" +
	"\n" +
	"client_cpu\x18\x06 \x01(\tR\tclientCpu\x12#\n" +
	"\rclient_memory\x18\a \x01(\tR\fclientMemory\x12,\n" +
	"\x12client_create_time\x18\b \x01(\tR\x10clientCreateTime\x125\n" +
	"\x17client_last_active_time\x18\t \x01(\tR\x14clientLastActiveTime\x12L\n" +
	"\x12client_task_status\x18\n" +
	" \x01(\x0e2\x1e.tasksmanager.ClientTaskStatusR\x10clientTaskStatus\x12/\n" +
	"\x11cpu_usage_percent\x18\v \x01(\x01H\x00R\x0fcpuUsagePercent\x88\x01\x01\x12/\n" +
	"\x11memory_used_bytes\x18\f \x01(\x03H\x01R\x0fmemoryUsedBytes\x88\x01\x01\x121\n" +
	"\x12memory_total_bytes\x18\r \x01(\x03H\x02R\x10memoryTotalBytes\x88\x01\x01\x12;\n" +
	"\x18network_rx_bytes_per_sec\x18\x0e \x01(\x01H\x03R\x14networkRxBytesPerSec\x88\x01\x01\x12;\n" +
	"\x18network_tx_bytes_per_sec\x18\x0f \x01(\x01H\x04R\x14networkTxBytesPerSec\x88\x01\x01\x12+\n" +
	"\x0fdisk_used_bytes\x18\x10 \x01(\x03H\x05R\rdiskUsedBytes\x88\x01\x01\x12-\n" +
	"\x10disk_total_bytes\x18\x11 \x01(\x03H\x06R\x0ediskTotalBytes\x88\x01\x01\x125\n" +
	"\x14resource_update_time\x18\x12 \x01(\tH\aR\x12resourceUpdateTime\x88\x01\x01B\x14\n" +
	"\x12_cpu_usage_percentB\x14\n" +
	"\x12_memory_used_bytesB\x15\n" +
	"\x13_memory_total_bytesB\x1b\n" +
	"\x19_network_rx_bytes_per_secB\x1b\n" +
	"\x19_network_tx_bytes_per_secB\x12\n" +
	"\x10_disk_used_bytesB\x13\n" +
	"\x11_disk_total_bytesB\x17\n" +
	"\x15_resource_update_time\"\x1b\n" +
	"\x19TaskClientInfoListRequest\"P\n" +
	"\x1aTaskClientInfoListResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.tasksmanager.TaskClientInfoR\x05items\"\x91\x01\n" +
	"\x16RegisterClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\fserver_nodes\x18\x03 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\vserverNodes\"\x7f\n" +
	"\x17ClientHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12J\n" +
	"\x10new_server_nodes\x18\x02 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\x0enewServerNodes\"\xc2\a\n" +
	"\x12GrpcServerNodeInfo\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x17\n" +
	"\anode_ip\x18\x03 \x01(\tR\x06nodeIp\x12\x1b\n" +
	"\tnode_port\x18\x04 \x01(\tR\bnodePort\x12\x1f\n" +
	"\vnode_system\x18\x05 \x01(\tR\n" +
	"nodeSystem\x12!\n" +
	"\fnode_version\x18\x06 \x01(\tR\vnodeVersion\x12\x19\n" +
	"\bnode_cpu\x18\a \x01(\tR\anodeCpu\x12\x1f\n" +
	"\vnode_memory\x18\b \x01(\tR\n" +
	"nodeMemory\x12(\n" +
	"\x10node_create_time\x18\t \x01(\tR\x0enodeCreateTime\x121\n" +
	"\x15node_last_active_time\x18\n" +
	" \x01(\tR\x12nodeLastActiveTime\x12/\n" +
	"\x11cpu_usage_percent\x18\v \x01(\x01H\x00R\x0fcpuUsagePercent\x88\x01\x01\x12/\n" +
	"\x11memory_used_bytes\x18\f \x01(\x03H\x01R\x0fmemoryUsedBytes\x88\x01\x01\x121\n" +
	"\x12memory_total_bytes\x18\r \x01(\x03H\x02R\x10memoryTotalBytes\x88\x01\x01\x12;\n" +
	"\x18network_rx_bytes_per_sec\x18\x0e \x01(\x01H\x03R\x14networkRxBytesPerSec\x88\x01\x01\x12;\n" +
	"\x18network_tx_bytes_per_sec\x18\x0f \x01(\x01H\x04R\x14networkTxBytesPerSec\x88\x01\x01\x12+\n" +
	"\x0fdisk_used_bytes\x18\x10 \x01(\x03H\x05R\rdiskUsedBytes\x88\x01\x01\x12-\n" +
	"\x10disk_total_bytes\x18\x11 \x01(\x03H\x06R\x0ediskTotalBytes\x88\x01\x01\x125\n" +
	"\x14resource_update_time\x18\x12 \x01(\tH\aR\x12resourceUpdateTime\x88\x01\x01B\x14\n" +
	"\x12_cpu_usage_percentB\x14\n" +
	"\x12_memory_used_bytesB\x15\n" +
	"\x13_memory_total_bytesB\x1b\n" +
	"\x19_network_rx_bytes_per_secB\x1b\n" +
	"\x19_network_tx_bytes_per_secB\x12\n" +
	"\x10_disk_used_bytesB\x13\n" +
	"\x11_disk_total_bytesB\x17\n" +
	"\x15_resource_update_time\"\x1f\n" +
	"\x1dGrpcServerNodeInfoListRequest\"X\n" +
	"\x1eGrpcServerNodeInfoListResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\x05items\"y\n" +
	"\x17NodeRegistrationRequest\x12=\n" +
	"\tnode_info\x18\x01 \x01(\v2 .tasksmanager.GrpcServerNodeInfoR\bnodeInfo\x12\x1f\n" +
	"\vknown_nodes\x18\x02 \x03(\tR\n" +
	"knownNodes\"\x91\x01\n" +
	"\x18NodeRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\vknown_nodes\x18\x03 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\n" +
	"knownNodes\"\x90\x01\n" +
	"\x14NodeHeartbeatRequest\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12=\n" +
	"\tnode_info\x18\x02 \x01(\v2 .tasksmanager.GrpcServerNodeInfoR\bnodeInfo\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"x\n" +
	"\x15NodeHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12E\n" +
	"\rupdated_nodes\x18\x02 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\fupdatedNodes\"\xee\x01\n" +
	"\vNodeMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x0efrom_node_uuid\x18\x02 \x01(\tR\ffromNodeUuid\x12 \n" +
	"\fto_node_uuid\x18\x03 \x01(\tR\n" +
	"toNodeUuid\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x15\n" +
	"\x03ttl\x18\a \x01(\x05H\x00R\x03ttl\x88\x01\x01B\x06\n" +
	"\x04_ttl\"I\n" +
	"\x12NodeMessageRequest\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.tasksmanager.NodeMessageR\amessage\"I\n" +
	"\x13NodeMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x97\x01\n" +
	"\x13SyncNodeListRequest\x120\n" +
	"\x14requesting_node_uuid\x18\x01 \x01(\tR\x12requestingNodeUuid\x12(\n" +
	"\x10known_node_uuids\x18\x02 \x03(\tR\x0eknownNodeUuids\x12$\n" +
	"\x0elast_sync_time\x18\x03 \x01(\x03R\flastSyncTime\"\xcc\x01\n" +
	"\x14SyncNodeListResponse\x12B\n" +
	"\fnodes_to_add\x18\x01 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\n" +
	"nodesToAdd\x12&\n" +
	"\x0fnodes_to_remove\x18\x02 \x03(\tR\rnodesToRemove\x12H\n" +
	"\x0fnodes_to_update\x18\x03 \x03(\v2 .tasksmanager.GrpcServerNodeInfoR\rnodesToUpdate\"\xa2\x03\n" +
	"\vTaskRequest\x12$\n" +
	"\x0etask_client_id\x18\x01 \x01(\tR\ftaskClientId\x123\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x16.tasksmanager.TaskTypeR\btaskType\x12\x18\n" +
	"\aTileKey\x18\x03 \x01(\tR\aTileKey\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x05R\x05epoch\x12'\n" +
	"\fimageryEpoch\x18\x05 \x01(\x05H\x00R\fimageryEpoch\x88\x01\x01\x12 \n" +
	"\ttask_body\x18\x06 \x01(\fH\x01R\btaskBody\x88\x01\x01\x12>\n" +
	"\vtask_method\x18\a \x01(\x0e2\x18.tasksmanager.TaskMethodH\x02R\n" +
	"taskMethod\x88\x01\x01\x12>\n" +
	"\vtask_status\x18\b \x01(\x0e2\x18.tasksmanager.TaskStatusH\x03R\n" +
	"taskStatus\x88\x01\x01B\x0f\n" +
	"\r_imageryEpochB\f\n" +
	"\n" +
	"_task_bodyB\x0e\n" +
	"\f_task_methodB\x0e\n" +
	"\f_task_status\"\xfb\x02\n" +
	"\fTaskResponse\x12$\n" +
	"\x0etask_client_id\x18\x01 \x01(\tR\ftaskClientId\x123\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x16.tasksmanager.TaskTypeR\btaskType\x12\x18\n" +
	"\aTileKey\x18\x03 \x01(\tR\aTileKey\x12\x14\n" +
	"\x05Epoch\x18\x04 \x01(\x05R\x05Epoch\x12'\n" +
	"\fimageryEpoch\x18\x05 \x01(\x05H\x00R\fimageryEpoch\x88\x01\x01\x121\n" +
	"\x12task_response_body\x18\x06 \x01(\fH\x01R\x10taskResponseBody\x88\x01\x01\x12>\n" +
	"\x19task_response_status_code\x18\a \x01(\x05H\x02R\x16taskResponseStatusCode\x88\x01\x01B\x0f\n" +
	"\r_imageryEpochB\x15\n" +
	"\x13_task_response_bodyB\x1c\n" +
	"\x1a_task_response_status_code*\xb5\x02\n" +
	"\bTaskType\x12\x15\n" +
	"\x11TASK_TYPE_UNKNOWN\x10\x00\x121\n" +
	"-TASK_TYPE_GOOGLE_EARTH_ROCKTREE_BULK_METADATA\x10\x01\x12-\n" +
	")TASK_TYPE_GOOGLE_EARTH_ROCKTREE_NODE_DATA\x10\x02\x12\x1d\n" +
	"\x19TASK_TYPE_GOOGLE_EARTH_Q2\x10\x03\x12\"\n" +
	"\x1eTASK_TYPE_GOOGLE_EARTH_IMAGERY\x10\x04\x12*\n" +
	"&TASK_TYPE_GOOGLE_EARTH_IMAGERY_HISTORY\x10\x05\x12\x1d\n" +
	"\x19TASK_TYPE_GOOGLE_EARTH_QP\x10\x06\x12\"\n" +
	"\x1eTASK_TYPE_GOOGLE_EARTH_TERRAIN\x10\a*t\n" +
	"\vTasksStatus\x12\x18\n" +
	"\x14TASKS_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14TASKS_STATUS_RUNNING\x10\x01\x12\x17\n" +
	"\x13TASKS_STATUS_PAUSED\x10\x02\x12\x18\n" +
	"\x14TASKS_STATUS_STOPPED\x10\x03*o\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_SUCCESS\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x03*\xb7\x01\n" +
	"\x10ClientTaskStatus\x12\x1e\n" +
	"\x1aCLIENT_TASK_STATUS_OFFLINE\x10\x00\x12\x1d\n" +
	"\x19CLIENT_TASK_STATUS_ONLINE\x10\x01\x12\x1b\n" +
	"\x17CLIENT_TASK_STATUS_AWAY\x10\x02\x12!\n" +
	"\x1dCLIENT_TASK_STATUS_CONNECTING\x10\x03\x12$\n" +
	" CLIENT_TASK_STATUS_DISCONNECTING\x10\x04*\xaa\x01\n" +
	"\n" +
	"TaskMethod\x12\x13\n" +
	"\x0fTASK_METHOD_GET\x10\x00\x12\x14\n" +
	"\x10TASK_METHOD_POST\x10\x01\x12\x13\n" +
	"\x0fTASK_METHOD_PUT\x10\x02\x12\x16\n" +
	"\x12TASK_METHOD_DELETE\x10\x03\x12\x15\n" +
	"\x11TASK_METHOD_PATCH\x10\x04\x12\x14\n" +
	"\x10TASK_METHOD_HEAD\x10\x05\x12\x17\n" +
	"\x13TASK_METHOD_OPTIONS\x10\x062\xcd\x06\n" +
	"\fTasksManager\x12j\n" +
	"\x15GetTaskClientInfoList\x12'.tasksmanager.TaskClientInfoListRequest\x1a(.tasksmanager.TaskClientInfoListResponse\x12v\n" +
	"\x19GetGrpcServerNodeInfoList\x12+.tasksmanager.GrpcServerNodeInfoListRequest\x1a,.tasksmanager.GrpcServerNodeInfoListResponse\x12C\n" +
	"\n" +
	"SubmitTask\x12\x19.tasksmanager.TaskRequest\x1a\x1a.tasksmanager.TaskResponse\x12T\n" +
	"\x0eRegisterClient\x12\x1c.tasksmanager.TaskClientInfo\x1a$.tasksmanager.RegisterClientResponse\x12V\n" +
	"\x0fClientHeartbeat\x12\x1c.tasksmanager.TaskClientInfo\x1a%.tasksmanager.ClientHeartbeatResponse\x12]\n" +
	"\fRegisterNode\x12%.tasksmanager.NodeRegistrationRequest\x1a&.tasksmanager.NodeRegistrationResponse\x12X\n" +
	"\rNodeHeartbeat\x12\".tasksmanager.NodeHeartbeatRequest\x1a#.tasksmanager.NodeHeartbeatResponse\x12V\n" +
	"\x0fSendNodeMessage\x12 .tasksmanager.NodeMessageRequest\x1a!.tasksmanager.NodeMessageResponse\x12U\n" +
	"\fSyncNodeList\x12!.tasksmanager.SyncNodeListRequest\x1a\".tasksmanager.SyncNodeListResponseB\x10Z\x0e./tasksmanagerb\x06proto3"

var (
	file_TasksManager_proto_rawDescOnce sync.Once
	file_TasksManager_proto_rawDescData []byte
)

func file_TasksManager_proto_rawDescGZIP() []byte {
	file_TasksManager_proto_rawDescOnce.Do(func() {
		file_TasksManager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TasksManager_proto_rawDesc), len(file_TasksManager_proto_rawDesc)))
	})
	return file_TasksManager_proto_rawDescData
}

var file_TasksManager_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_TasksManager_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_TasksManager_proto_goTypes = []any{
	(TaskType)(0),                          // 0: tasksmanager.TaskType
	(TasksStatus)(0),                       // 1: tasksmanager.TasksStatus
	(TaskStatus)(0),                        // 2: tasksmanager.TaskStatus
	(ClientTaskStatus)(0),                  // 3: tasksmanager.ClientTaskStatus
	(TaskMethod)(0),                        // 4: tasksmanager.TaskMethod
	(*TaskClientInfo)(nil),                 // 5: tasksmanager.TaskClientInfo
	(*TaskClientInfoListRequest)(nil),      // 6: tasksmanager.TaskClientInfoListRequest
	(*TaskClientInfoListResponse)(nil),     // 7: tasksmanager.TaskClientInfoListResponse
	(*RegisterClientResponse)(nil),         // 8: tasksmanager.RegisterClientResponse
	(*ClientHeartbeatResponse)(nil),        // 9: tasksmanager.ClientHeartbeatResponse
	(*GrpcServerNodeInfo)(nil),             // 10: tasksmanager.GrpcServerNodeInfo
	(*GrpcServerNodeInfoListRequest)(nil),  // 11: tasksmanager.GrpcServerNodeInfoListRequest
	(*GrpcServerNodeInfoListResponse)(nil), // 12: tasksmanager.GrpcServerNodeInfoListResponse
	(*NodeRegistrationRequest)(nil),        // 13: tasksmanager.NodeRegistrationRequest
	(*NodeRegistrationResponse)(nil),       // 14: tasksmanager.NodeRegistrationResponse
	(*NodeHeartbeatRequest)(nil),           // 15: tasksmanager.NodeHeartbeatRequest
	(*NodeHeartbeatResponse)(nil),          // 16: tasksmanager.NodeHeartbeatResponse
	(*NodeMessage)(nil),                    // 17: tasksmanager.NodeMessage
	(*NodeMessageRequest)(nil),             // 18: tasksmanager.NodeMessageRequest
	(*NodeMessageResponse)(nil),            // 19: tasksmanager.NodeMessageResponse
	(*SyncNodeListRequest)(nil),            // 20: tasksmanager.SyncNodeListRequest
	(*SyncNodeListResponse)(nil),           // 21: tasksmanager.SyncNodeListResponse
	(*TaskRequest)(nil),                    // 22: tasksmanager.TaskRequest
	(*TaskResponse)(nil),                   // 23: tasksmanager.TaskResponse
}
var file_TasksManager_proto_depIdxs = []int32{
	3,  // 0: tasksmanager.TaskClientInfo.client_task_status:type_name -> tasksmanager.ClientTaskStatus
	5,  // 1: tasksmanager.TaskClientInfoListResponse.items:type_name -> tasksmanager.TaskClientInfo
	10, // 2: tasksmanager.RegisterClientResponse.server_nodes:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 3: tasksmanager.ClientHeartbeatResponse.new_server_nodes:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 4: tasksmanager.GrpcServerNodeInfoListResponse.items:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 5: tasksmanager.NodeRegistrationRequest.node_info:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 6: tasksmanager.NodeRegistrationResponse.known_nodes:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 7: tasksmanager.NodeHeartbeatRequest.node_info:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 8: tasksmanager.NodeHeartbeatResponse.updated_nodes:type_name -> tasksmanager.GrpcServerNodeInfo
	17, // 9: tasksmanager.NodeMessageRequest.message:type_name -> tasksmanager.NodeMessage
	10, // 10: tasksmanager.SyncNodeListResponse.nodes_to_add:type_name -> tasksmanager.GrpcServerNodeInfo
	10, // 11: tasksmanager.SyncNodeListResponse.nodes_to_update:type_name -> tasksmanager.GrpcServerNodeInfo
	0,  // 12: tasksmanager.TaskRequest.task_type:type_name -> tasksmanager.TaskType
	4,  // 13: tasksmanager.TaskRequest.task_method:type_name -> tasksmanager.TaskMethod
	2,  // 14: tasksmanager.TaskRequest.task_status:type_name -> tasksmanager.TaskStatus
	0,  // 15: tasksmanager.TaskResponse.task_type:type_name -> tasksmanager.TaskType
	6,  // 16: tasksmanager.TasksManager.GetTaskClientInfoList:input_type -> tasksmanager.TaskClientInfoListRequest
	11, // 17: tasksmanager.TasksManager.GetGrpcServerNodeInfoList:input_type -> tasksmanager.GrpcServerNodeInfoListRequest
	22, // 18: tasksmanager.TasksManager.SubmitTask:input_type -> tasksmanager.TaskRequest
	5,  // 19: tasksmanager.TasksManager.RegisterClient:input_type -> tasksmanager.TaskClientInfo
	5,  // 20: tasksmanager.TasksManager.ClientHeartbeat:input_type -> tasksmanager.TaskClientInfo
	13, // 21: tasksmanager.TasksManager.RegisterNode:input_type -> tasksmanager.NodeRegistrationRequest
	15, // 22: tasksmanager.TasksManager.NodeHeartbeat:input_type -> tasksmanager.NodeHeartbeatRequest
	18, // 23: tasksmanager.TasksManager.SendNodeMessage:input_type -> tasksmanager.NodeMessageRequest
	20, // 24: tasksmanager.TasksManager.SyncNodeList:input_type -> tasksmanager.SyncNodeListRequest
	7,  // 25: tasksmanager.TasksManager.GetTaskClientInfoList:output_type -> tasksmanager.TaskClientInfoListResponse
	12, // 26: tasksmanager.TasksManager.GetGrpcServerNodeInfoList:output_type -> tasksmanager.GrpcServerNodeInfoListResponse
	23, // 27: tasksmanager.TasksManager.SubmitTask:output_type -> tasksmanager.TaskResponse
	8,  // 28: tasksmanager.TasksManager.RegisterClient:output_type -> tasksmanager.RegisterClientResponse
	9,  // 29: tasksmanager.TasksManager.ClientHeartbeat:output_type -> tasksmanager.ClientHeartbeatResponse
	14, // 30: tasksmanager.TasksManager.RegisterNode:output_type -> tasksmanager.NodeRegistrationResponse
	16, // 31: tasksmanager.TasksManager.NodeHeartbeat:output_type -> tasksmanager.NodeHeartbeatResponse
	19, // 32: tasksmanager.TasksManager.SendNodeMessage:output_type -> tasksmanager.NodeMessageResponse
	21, // 33: tasksmanager.TasksManager.SyncNodeList:output_type -> tasksmanager.SyncNodeListResponse
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_TasksManager_proto_init() }
func file_TasksManager_proto_init() {
	if File_TasksManager_proto != nil {
		return
	}
	file_TasksManager_proto_msgTypes[0].OneofWrappers = []any{}
	file_TasksManager_proto_msgTypes[5].OneofWrappers = []any{}
	file_TasksManager_proto_msgTypes[12].OneofWrappers = []any{}
	file_TasksManager_proto_msgTypes[17].OneofWrappers = []any{}
	file_TasksManager_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TasksManager_proto_rawDesc), len(file_TasksManager_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TasksManager_proto_goTypes,
		DependencyIndexes: file_TasksManager_proto_depIdxs,
		EnumInfos:         file_TasksManager_proto_enumTypes,
		MessageInfos:      file_TasksManager_proto_msgTypes,
	}.Build()
	File_TasksManager_proto = out.File
	file_TasksManager_proto_goTypes = nil
	file_TasksManager_proto_depIdxs = nil
}
