// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: quadtreeset.proto

package GoogleEarth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LayerType 图层类型枚举
type QuadtreeLayer_LayerType int32

const (
	QuadtreeLayer_LAYER_TYPE_IMAGERY         QuadtreeLayer_LayerType = 0 // 影像图层
	QuadtreeLayer_LAYER_TYPE_TERRAIN         QuadtreeLayer_LayerType = 1 // 地形图层
	QuadtreeLayer_LAYER_TYPE_VECTOR          QuadtreeLayer_LayerType = 2 // 矢量图层
	QuadtreeLayer_LAYER_TYPE_IMAGERY_HISTORY QuadtreeLayer_LayerType = 3 // 影像历史图层
)

// Enum value maps for QuadtreeLayer_LayerType.
var (
	QuadtreeLayer_LayerType_name = map[int32]string{
		0: "LAYER_TYPE_IMAGERY",
		1: "LAYER_TYPE_TERRAIN",
		2: "LAYER_TYPE_VECTOR",
		3: "LAYER_TYPE_IMAGERY_HISTORY",
	}
	QuadtreeLayer_LayerType_value = map[string]int32{
		"LAYER_TYPE_IMAGERY":         0,
		"LAYER_TYPE_TERRAIN":         1,
		"LAYER_TYPE_VECTOR":          2,
		"LAYER_TYPE_IMAGERY_HISTORY": 3,
	}
)

func (x QuadtreeLayer_LayerType) Enum() *QuadtreeLayer_LayerType {
	p := new(QuadtreeLayer_LayerType)
	*p = x
	return p
}

func (x QuadtreeLayer_LayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuadtreeLayer_LayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_quadtreeset_proto_enumTypes[0].Descriptor()
}

func (QuadtreeLayer_LayerType) Type() protoreflect.EnumType {
	return &file_quadtreeset_proto_enumTypes[0]
}

func (x QuadtreeLayer_LayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QuadtreeLayer_LayerType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QuadtreeLayer_LayerType(num)
	return nil
}

// Deprecated: Use QuadtreeLayer_LayerType.Descriptor instead.
func (QuadtreeLayer_LayerType) EnumDescriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{4, 0}
}

// NodeFlags 节点标志枚举
type QuadtreeNode_NodeFlags int32

const (
	QuadtreeNode_NODE_FLAGS_CHILD_COUNT  QuadtreeNode_NodeFlags = 4 // 节点标志子节点计数
	QuadtreeNode_NODE_FLAGS_CACHE_BIT    QuadtreeNode_NodeFlags = 4 // 节点标志缓存位
	QuadtreeNode_NODE_FLAGS_DRAWABLE_BIT QuadtreeNode_NodeFlags = 5 // 节点标志可绘制位
	QuadtreeNode_NODE_FLAGS_IMAGE_BIT    QuadtreeNode_NodeFlags = 6 // 节点标志图像位
	QuadtreeNode_NODE_FLAGS_TERRAIN_BIT  QuadtreeNode_NodeFlags = 7 // 节点标志地形位
)

// Enum value maps for QuadtreeNode_NodeFlags.
var (
	QuadtreeNode_NodeFlags_name = map[int32]string{
		4: "NODE_FLAGS_CHILD_COUNT",
		// Duplicate value: 4: "NODE_FLAGS_CACHE_BIT",
		5: "NODE_FLAGS_DRAWABLE_BIT",
		6: "NODE_FLAGS_IMAGE_BIT",
		7: "NODE_FLAGS_TERRAIN_BIT",
	}
	QuadtreeNode_NodeFlags_value = map[string]int32{
		"NODE_FLAGS_CHILD_COUNT":  4,
		"NODE_FLAGS_CACHE_BIT":    4,
		"NODE_FLAGS_DRAWABLE_BIT": 5,
		"NODE_FLAGS_IMAGE_BIT":    6,
		"NODE_FLAGS_TERRAIN_BIT":  7,
	}
)

func (x QuadtreeNode_NodeFlags) Enum() *QuadtreeNode_NodeFlags {
	p := new(QuadtreeNode_NodeFlags)
	*p = x
	return p
}

func (x QuadtreeNode_NodeFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuadtreeNode_NodeFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_quadtreeset_proto_enumTypes[1].Descriptor()
}

func (QuadtreeNode_NodeFlags) Type() protoreflect.EnumType {
	return &file_quadtreeset_proto_enumTypes[1]
}

func (x QuadtreeNode_NodeFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QuadtreeNode_NodeFlags) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QuadtreeNode_NodeFlags(num)
	return nil
}

// Deprecated: Use QuadtreeNode_NodeFlags.Descriptor instead.
func (QuadtreeNode_NodeFlags) EnumDescriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{5, 0}
}

// QuadtreeChannel 四叉树通道
type QuadtreeChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *int32                 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`                                     // 类型
	ChannelEpoch  *int32                 `protobuf:"varint,2,req,name=channel_epoch,json=channelEpoch" json:"channel_epoch,omitempty"` // 通道时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuadtreeChannel) Reset() {
	*x = QuadtreeChannel{}
	mi := &file_quadtreeset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreeChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreeChannel) ProtoMessage() {}

func (x *QuadtreeChannel) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreeChannel.ProtoReflect.Descriptor instead.
func (*QuadtreeChannel) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{0}
}

func (x *QuadtreeChannel) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *QuadtreeChannel) GetChannelEpoch() int32 {
	if x != nil && x.ChannelEpoch != nil {
		return *x.ChannelEpoch
	}
	return 0
}

// QuadtreeImageryTimedTile 四叉树影像定时瓦片
type QuadtreeImageryTimedTile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds   *int32                 `protobuf:"varint,1,req,name=milliseconds" json:"milliseconds,omitempty"`                             // 毫秒数
	TimedTileEpoch *int32                 `protobuf:"varint,2,req,name=timed_tile_epoch,json=timedTileEpoch" json:"timed_tile_epoch,omitempty"` // 定时瓦片时间戳
	Provider       *int32                 `protobuf:"varint,3,opt,name=provider" json:"provider,omitempty"`                                     // 提供商
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuadtreeImageryTimedTile) Reset() {
	*x = QuadtreeImageryTimedTile{}
	mi := &file_quadtreeset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreeImageryTimedTile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreeImageryTimedTile) ProtoMessage() {}

func (x *QuadtreeImageryTimedTile) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreeImageryTimedTile.ProtoReflect.Descriptor instead.
func (*QuadtreeImageryTimedTile) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{1}
}

func (x *QuadtreeImageryTimedTile) GetMilliseconds() int32 {
	if x != nil && x.Milliseconds != nil {
		return *x.Milliseconds
	}
	return 0
}

func (x *QuadtreeImageryTimedTile) GetTimedTileEpoch() int32 {
	if x != nil && x.TimedTileEpoch != nil {
		return *x.TimedTileEpoch
	}
	return 0
}

func (x *QuadtreeImageryTimedTile) GetProvider() int32 {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return 0
}

// QuadtreeImageryDatedTile 四叉树影像日期瓦片
type QuadtreeImageryDatedTile struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Date           *int32                      `protobuf:"varint,1,req,name=date" json:"date,omitempty"`                                             // 日期
	DatedTileEpoch *int32                      `protobuf:"varint,2,req,name=dated_tile_epoch,json=datedTileEpoch" json:"dated_tile_epoch,omitempty"` // 日期瓦片时间戳
	Provider       *int32                      `protobuf:"varint,3,req,name=provider" json:"provider,omitempty"`                                     // 提供商
	TimedTiles     []*QuadtreeImageryTimedTile `protobuf:"bytes,4,rep,name=timed_tiles,json=timedTiles" json:"timed_tiles,omitempty"`                // 定时瓦片列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuadtreeImageryDatedTile) Reset() {
	*x = QuadtreeImageryDatedTile{}
	mi := &file_quadtreeset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreeImageryDatedTile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreeImageryDatedTile) ProtoMessage() {}

func (x *QuadtreeImageryDatedTile) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreeImageryDatedTile.ProtoReflect.Descriptor instead.
func (*QuadtreeImageryDatedTile) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{2}
}

func (x *QuadtreeImageryDatedTile) GetDate() int32 {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return 0
}

func (x *QuadtreeImageryDatedTile) GetDatedTileEpoch() int32 {
	if x != nil && x.DatedTileEpoch != nil {
		return *x.DatedTileEpoch
	}
	return 0
}

func (x *QuadtreeImageryDatedTile) GetProvider() int32 {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return 0
}

func (x *QuadtreeImageryDatedTile) GetTimedTiles() []*QuadtreeImageryTimedTile {
	if x != nil {
		return x.TimedTiles
	}
	return nil
}

// QuadtreeImageryDates 四叉树影像日期
type QuadtreeImageryDates struct {
	state                  protoimpl.MessageState      `protogen:"open.v1"`
	DatedTile              []*QuadtreeImageryDatedTile `protobuf:"bytes,1,rep,name=dated_tile,json=datedTile" json:"dated_tile,omitempty"`                                           // 日期瓦片列表
	SharedTileDate         *int32                      `protobuf:"varint,2,opt,name=shared_tile_date,json=sharedTileDate" json:"shared_tile_date,omitempty"`                         // 共享瓦片日期
	CoarseTileDates        []int32                     `protobuf:"varint,3,rep,name=coarse_tile_dates,json=coarseTileDates" json:"coarse_tile_dates,omitempty"`                      // 粗瓦片日期列表
	SharedTileMilliseconds *int32                      `protobuf:"varint,4,opt,name=shared_tile_milliseconds,json=sharedTileMilliseconds" json:"shared_tile_milliseconds,omitempty"` // 共享瓦片毫秒数
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QuadtreeImageryDates) Reset() {
	*x = QuadtreeImageryDates{}
	mi := &file_quadtreeset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreeImageryDates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreeImageryDates) ProtoMessage() {}

func (x *QuadtreeImageryDates) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreeImageryDates.ProtoReflect.Descriptor instead.
func (*QuadtreeImageryDates) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{3}
}

func (x *QuadtreeImageryDates) GetDatedTile() []*QuadtreeImageryDatedTile {
	if x != nil {
		return x.DatedTile
	}
	return nil
}

func (x *QuadtreeImageryDates) GetSharedTileDate() int32 {
	if x != nil && x.SharedTileDate != nil {
		return *x.SharedTileDate
	}
	return 0
}

func (x *QuadtreeImageryDates) GetCoarseTileDates() []int32 {
	if x != nil {
		return x.CoarseTileDates
	}
	return nil
}

func (x *QuadtreeImageryDates) GetSharedTileMilliseconds() int32 {
	if x != nil && x.SharedTileMilliseconds != nil {
		return *x.SharedTileMilliseconds
	}
	return 0
}

// QuadtreeLayer 四叉树图层
type QuadtreeLayer struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          *QuadtreeLayer_LayerType `protobuf:"varint,1,req,name=type,enum=GoogleEarth.Q2.QuadtreeLayer_LayerType" json:"type,omitempty"` // 类型
	LayerEpoch    *int32                   `protobuf:"varint,2,req,name=layer_epoch,json=layerEpoch" json:"layer_epoch,omitempty"`               // 图层时间戳
	Provider      *int32                   `protobuf:"varint,3,opt,name=provider" json:"provider,omitempty"`                                     // 提供商
	DatesLayer    *QuadtreeImageryDates    `protobuf:"bytes,4,opt,name=dates_layer,json=datesLayer" json:"dates_layer,omitempty"`                // 日期图层
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuadtreeLayer) Reset() {
	*x = QuadtreeLayer{}
	mi := &file_quadtreeset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreeLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreeLayer) ProtoMessage() {}

func (x *QuadtreeLayer) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreeLayer.ProtoReflect.Descriptor instead.
func (*QuadtreeLayer) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{4}
}

func (x *QuadtreeLayer) GetType() QuadtreeLayer_LayerType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuadtreeLayer_LAYER_TYPE_IMAGERY
}

func (x *QuadtreeLayer) GetLayerEpoch() int32 {
	if x != nil && x.LayerEpoch != nil {
		return *x.LayerEpoch
	}
	return 0
}

func (x *QuadtreeLayer) GetProvider() int32 {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return 0
}

func (x *QuadtreeLayer) GetDatesLayer() *QuadtreeImageryDates {
	if x != nil {
		return x.DatesLayer
	}
	return nil
}

// QuadtreeNode 四叉树节点
type QuadtreeNode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Flags          *int32                 `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`                                           // 标志位
	CacheNodeEpoch *int32                 `protobuf:"varint,2,opt,name=cache_node_epoch,json=cacheNodeEpoch" json:"cache_node_epoch,omitempty"` // 缓存节点时间戳
	Layer          []*QuadtreeLayer       `protobuf:"bytes,3,rep,name=layer" json:"layer,omitempty"`                                            // 图层列表
	Channel        []*QuadtreeChannel     `protobuf:"bytes,4,rep,name=channel" json:"channel,omitempty"`                                        // 通道列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuadtreeNode) Reset() {
	*x = QuadtreeNode{}
	mi := &file_quadtreeset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreeNode) ProtoMessage() {}

func (x *QuadtreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreeNode.ProtoReflect.Descriptor instead.
func (*QuadtreeNode) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{5}
}

func (x *QuadtreeNode) GetFlags() int32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *QuadtreeNode) GetCacheNodeEpoch() int32 {
	if x != nil && x.CacheNodeEpoch != nil {
		return *x.CacheNodeEpoch
	}
	return 0
}

func (x *QuadtreeNode) GetLayer() []*QuadtreeLayer {
	if x != nil {
		return x.Layer
	}
	return nil
}

func (x *QuadtreeNode) GetChannel() []*QuadtreeChannel {
	if x != nil {
		return x.Channel
	}
	return nil
}

// QuadtreePacket 四叉树数据包
type QuadtreePacket struct {
	state              protoimpl.MessageState               `protogen:"open.v1"`
	PacketEpoch        *int32                               `protobuf:"varint,1,req,name=packet_epoch,json=packetEpoch" json:"packet_epoch,omitempty"` // 数据包时间戳
	Sparsequadtreenode []*QuadtreePacket_SparseQuadtreeNode `protobuf:"group,2,rep,name=SparseQuadtreeNode,json=sparsequadtreenode" json:"sparsequadtreenode,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuadtreePacket) Reset() {
	*x = QuadtreePacket{}
	mi := &file_quadtreeset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreePacket) ProtoMessage() {}

func (x *QuadtreePacket) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreePacket.ProtoReflect.Descriptor instead.
func (*QuadtreePacket) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{6}
}

func (x *QuadtreePacket) GetPacketEpoch() int32 {
	if x != nil && x.PacketEpoch != nil {
		return *x.PacketEpoch
	}
	return 0
}

func (x *QuadtreePacket) GetSparsequadtreenode() []*QuadtreePacket_SparseQuadtreeNode {
	if x != nil {
		return x.Sparsequadtreenode
	}
	return nil
}

// SparseQuadtreeNode 稀疏四叉树节点组
type QuadtreePacket_SparseQuadtreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *int32                 `protobuf:"varint,3,req,name=index" json:"index,omitempty"` // 索引
	Node          *QuadtreeNode          `protobuf:"bytes,4,req,name=Node" json:"Node,omitempty"`    // 节点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuadtreePacket_SparseQuadtreeNode) Reset() {
	*x = QuadtreePacket_SparseQuadtreeNode{}
	mi := &file_quadtreeset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadtreePacket_SparseQuadtreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadtreePacket_SparseQuadtreeNode) ProtoMessage() {}

func (x *QuadtreePacket_SparseQuadtreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_quadtreeset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadtreePacket_SparseQuadtreeNode.ProtoReflect.Descriptor instead.
func (*QuadtreePacket_SparseQuadtreeNode) Descriptor() ([]byte, []int) {
	return file_quadtreeset_proto_rawDescGZIP(), []int{6, 0}
}

func (x *QuadtreePacket_SparseQuadtreeNode) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *QuadtreePacket_SparseQuadtreeNode) GetNode() *QuadtreeNode {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_quadtreeset_proto protoreflect.FileDescriptor

var file_quadtreeset_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x71, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68,
	0x2e, 0x51, 0x32, 0x22, 0x4a, 0x0a, 0x0f, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x22,
	0x84, 0x01, 0x0a, 0x18, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x0c, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65,
	0x64, 0x54, 0x69, 0x6c, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0xbf, 0x01, 0x0a, 0x18, 0x51, 0x75, 0x61, 0x64, 0x74,
	0x72, 0x65, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x45, 0x70, 0x6f, 0x63,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x49, 0x0a,
	0x0b, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68,
	0x2e, 0x51, 0x32, 0x2e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x74, 0x69,
	0x6d, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x14, 0x51, 0x75, 0x61,
	0x64, 0x74, 0x72, 0x65, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x47, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61,
	0x72, 0x74, 0x68, 0x2e, 0x51, 0x32, 0x2e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x52,
	0x09, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x6f, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x74,
	0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0f, 0x63, 0x6f, 0x61, 0x72, 0x73, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x38, 0x0a, 0x18, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x5f,
	0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x16, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x4d, 0x69,
	0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0xc4, 0x02, 0x0a, 0x0d, 0x51,
	0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x51, 0x32, 0x2e, 0x51, 0x75, 0x61, 0x64,
	0x74, 0x72, 0x65, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x73, 0x5f,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x47, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x51, 0x32, 0x2e, 0x51, 0x75, 0x61,
	0x64, 0x74, 0x72, 0x65, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x73, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x72, 0x0a,
	0x09, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x52, 0x59,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x54, 0x45, 0x52, 0x52, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x49, 0x4d, 0x41, 0x47, 0x45, 0x52, 0x59, 0x5f, 0x48, 0x49, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x10,
	0x03, 0x22, 0xd9, 0x02, 0x0a, 0x0c, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x70, 0x6f,
	0x63, 0x68, 0x12, 0x33, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e,
	0x51, 0x32, 0x2e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x51, 0x32, 0x2e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72,
	0x65, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x22, 0x98, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x47, 0x53, 0x5f, 0x43,
	0x48, 0x49, 0x4c, 0x44, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14,
	0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x47, 0x53, 0x5f, 0x43, 0x41, 0x43, 0x48, 0x45,
	0x5f, 0x42, 0x49, 0x54, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x46,
	0x4c, 0x41, 0x47, 0x53, 0x5f, 0x44, 0x52, 0x41, 0x57, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x42, 0x49,
	0x54, 0x10, 0x05, 0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x47,
	0x53, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x42, 0x49, 0x54, 0x10, 0x06, 0x12, 0x1a, 0x0a,
	0x16, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x47, 0x53, 0x5f, 0x54, 0x45, 0x52, 0x52,
	0x41, 0x49, 0x4e, 0x5f, 0x42, 0x49, 0x54, 0x10, 0x07, 0x1a, 0x02, 0x10, 0x01, 0x22, 0xf4, 0x01,
	0x0a, 0x0e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x70,
	0x6f, 0x63, 0x68, 0x12, 0x61, 0x0a, 0x12, 0x73, 0x70, 0x61, 0x72, 0x73, 0x65, 0x71, 0x75, 0x61,
	0x64, 0x74, 0x72, 0x65, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0a, 0x32,
	0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x51, 0x32,
	0x2e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x53, 0x70, 0x61, 0x72, 0x73, 0x65, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x12, 0x73, 0x70, 0x61, 0x72, 0x73, 0x65, 0x71, 0x75, 0x61, 0x64, 0x74, 0x72,
	0x65, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x1a, 0x5c, 0x0a, 0x12, 0x53, 0x70, 0x61, 0x72, 0x73, 0x65,
	0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x30, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x51,
	0x32, 0x2e, 0x51, 0x75, 0x61, 0x64, 0x74, 0x72, 0x65, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x4e, 0x6f, 0x64, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x45, 0x61, 0x72, 0x74, 0x68,
})

var (
	file_quadtreeset_proto_rawDescOnce sync.Once
	file_quadtreeset_proto_rawDescData []byte
)

func file_quadtreeset_proto_rawDescGZIP() []byte {
	file_quadtreeset_proto_rawDescOnce.Do(func() {
		file_quadtreeset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quadtreeset_proto_rawDesc), len(file_quadtreeset_proto_rawDesc)))
	})
	return file_quadtreeset_proto_rawDescData
}

var file_quadtreeset_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_quadtreeset_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_quadtreeset_proto_goTypes = []any{
	(QuadtreeLayer_LayerType)(0),              // 0: GoogleEarth.Q2.QuadtreeLayer.LayerType
	(QuadtreeNode_NodeFlags)(0),               // 1: GoogleEarth.Q2.QuadtreeNode.NodeFlags
	(*QuadtreeChannel)(nil),                   // 2: GoogleEarth.Q2.QuadtreeChannel
	(*QuadtreeImageryTimedTile)(nil),          // 3: GoogleEarth.Q2.QuadtreeImageryTimedTile
	(*QuadtreeImageryDatedTile)(nil),          // 4: GoogleEarth.Q2.QuadtreeImageryDatedTile
	(*QuadtreeImageryDates)(nil),              // 5: GoogleEarth.Q2.QuadtreeImageryDates
	(*QuadtreeLayer)(nil),                     // 6: GoogleEarth.Q2.QuadtreeLayer
	(*QuadtreeNode)(nil),                      // 7: GoogleEarth.Q2.QuadtreeNode
	(*QuadtreePacket)(nil),                    // 8: GoogleEarth.Q2.QuadtreePacket
	(*QuadtreePacket_SparseQuadtreeNode)(nil), // 9: GoogleEarth.Q2.QuadtreePacket.SparseQuadtreeNode
}
var file_quadtreeset_proto_depIdxs = []int32{
	3, // 0: GoogleEarth.Q2.QuadtreeImageryDatedTile.timed_tiles:type_name -> GoogleEarth.Q2.QuadtreeImageryTimedTile
	4, // 1: GoogleEarth.Q2.QuadtreeImageryDates.dated_tile:type_name -> GoogleEarth.Q2.QuadtreeImageryDatedTile
	0, // 2: GoogleEarth.Q2.QuadtreeLayer.type:type_name -> GoogleEarth.Q2.QuadtreeLayer.LayerType
	5, // 3: GoogleEarth.Q2.QuadtreeLayer.dates_layer:type_name -> GoogleEarth.Q2.QuadtreeImageryDates
	6, // 4: GoogleEarth.Q2.QuadtreeNode.layer:type_name -> GoogleEarth.Q2.QuadtreeLayer
	2, // 5: GoogleEarth.Q2.QuadtreeNode.channel:type_name -> GoogleEarth.Q2.QuadtreeChannel
	9, // 6: GoogleEarth.Q2.QuadtreePacket.sparsequadtreenode:type_name -> GoogleEarth.Q2.QuadtreePacket.SparseQuadtreeNode
	7, // 7: GoogleEarth.Q2.QuadtreePacket.SparseQuadtreeNode.Node:type_name -> GoogleEarth.Q2.QuadtreeNode
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_quadtreeset_proto_init() }
func file_quadtreeset_proto_init() {
	if File_quadtreeset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quadtreeset_proto_rawDesc), len(file_quadtreeset_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quadtreeset_proto_goTypes,
		DependencyIndexes: file_quadtreeset_proto_depIdxs,
		EnumInfos:         file_quadtreeset_proto_enumTypes,
		MessageInfos:      file_quadtreeset_proto_msgTypes,
	}.Build()
	File_quadtreeset_proto = out.File
	file_quadtreeset_proto_goTypes = nil
	file_quadtreeset_proto_depIdxs = nil
}
