// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: streaming_imagery.proto

package GoogleEarth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Codec 编解码器枚举
type EarthImageryPacket_Codec int32

const (
	EarthImageryPacket_JPEG     EarthImageryPacket_Codec = 0 // JPEG格式
	EarthImageryPacket_JPEG2000 EarthImageryPacket_Codec = 1 // JPEG2000格式
	EarthImageryPacket_DXT1     EarthImageryPacket_Codec = 2 // DXT1压缩格式
	EarthImageryPacket_DXT5     EarthImageryPacket_Codec = 3 // DXT5压缩格式
	EarthImageryPacket_PNG_RGBA EarthImageryPacket_Codec = 4 // PNG RGBA格式
)

// Enum value maps for EarthImageryPacket_Codec.
var (
	EarthImageryPacket_Codec_name = map[int32]string{
		0: "JPEG",
		1: "JPEG2000",
		2: "DXT1",
		3: "DXT5",
		4: "PNG_RGBA",
	}
	EarthImageryPacket_Codec_value = map[string]int32{
		"JPEG":     0,
		"JPEG2000": 1,
		"DXT1":     2,
		"DXT5":     3,
		"PNG_RGBA": 4,
	}
)

func (x EarthImageryPacket_Codec) Enum() *EarthImageryPacket_Codec {
	p := new(EarthImageryPacket_Codec)
	*p = x
	return p
}

func (x EarthImageryPacket_Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarthImageryPacket_Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_streaming_imagery_proto_enumTypes[0].Descriptor()
}

func (EarthImageryPacket_Codec) Type() protoreflect.EnumType {
	return &file_streaming_imagery_proto_enumTypes[0]
}

func (x EarthImageryPacket_Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarthImageryPacket_Codec) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarthImageryPacket_Codec(num)
	return nil
}

// Deprecated: Use EarthImageryPacket_Codec.Descriptor instead.
func (EarthImageryPacket_Codec) EnumDescriptor() ([]byte, []int) {
	return file_streaming_imagery_proto_rawDescGZIP(), []int{0, 0}
}

// SeparateAlphaType 独立Alpha通道类型枚举
type EarthImageryPacket_SeparateAlphaType int32

const (
	EarthImageryPacket_NONE       EarthImageryPacket_SeparateAlphaType = 0 // 无Alpha通道
	EarthImageryPacket_PNG        EarthImageryPacket_SeparateAlphaType = 1 // PNG格式Alpha通道
	EarthImageryPacket_JPEG_ALPHA EarthImageryPacket_SeparateAlphaType = 2 // JPEG Alpha格式
	EarthImageryPacket_RLE_1_BIT  EarthImageryPacket_SeparateAlphaType = 3 // RLE 1位Alpha通道
)

// Enum value maps for EarthImageryPacket_SeparateAlphaType.
var (
	EarthImageryPacket_SeparateAlphaType_name = map[int32]string{
		0: "NONE",
		1: "PNG",
		2: "JPEG_ALPHA",
		3: "RLE_1_BIT",
	}
	EarthImageryPacket_SeparateAlphaType_value = map[string]int32{
		"NONE":       0,
		"PNG":        1,
		"JPEG_ALPHA": 2,
		"RLE_1_BIT":  3,
	}
)

func (x EarthImageryPacket_SeparateAlphaType) Enum() *EarthImageryPacket_SeparateAlphaType {
	p := new(EarthImageryPacket_SeparateAlphaType)
	*p = x
	return p
}

func (x EarthImageryPacket_SeparateAlphaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarthImageryPacket_SeparateAlphaType) Descriptor() protoreflect.EnumDescriptor {
	return file_streaming_imagery_proto_enumTypes[1].Descriptor()
}

func (EarthImageryPacket_SeparateAlphaType) Type() protoreflect.EnumType {
	return &file_streaming_imagery_proto_enumTypes[1]
}

func (x EarthImageryPacket_SeparateAlphaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarthImageryPacket_SeparateAlphaType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarthImageryPacket_SeparateAlphaType(num)
	return nil
}

// Deprecated: Use EarthImageryPacket_SeparateAlphaType.Descriptor instead.
func (EarthImageryPacket_SeparateAlphaType) EnumDescriptor() ([]byte, []int) {
	return file_streaming_imagery_proto_rawDescGZIP(), []int{0, 1}
}

// EarthImageryPacket 地球影像数据包
type EarthImageryPacket struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	ImageType     *EarthImageryPacket_Codec             `protobuf:"varint,1,opt,name=image_type,json=imageType,enum=GoogleEarth.EarthImageryPacket_Codec,def=0" json:"image_type,omitempty"`             // 图像类型，默认为JPEG
	ImageData     []byte                                `protobuf:"bytes,2,opt,name=image_data,json=imageData" json:"image_data,omitempty"`                                                              // 图像数据
	AlphaType     *EarthImageryPacket_SeparateAlphaType `protobuf:"varint,3,opt,name=alpha_type,json=alphaType,enum=GoogleEarth.EarthImageryPacket_SeparateAlphaType,def=0" json:"alpha_type,omitempty"` // Alpha通道类型，默认为NONE
	ImageAlpha    []byte                                `protobuf:"bytes,4,opt,name=image_alpha,json=imageAlpha" json:"image_alpha,omitempty"`                                                           // 图像Alpha通道数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for EarthImageryPacket fields.
const (
	Default_EarthImageryPacket_ImageType = EarthImageryPacket_JPEG
	Default_EarthImageryPacket_AlphaType = EarthImageryPacket_NONE
)

func (x *EarthImageryPacket) Reset() {
	*x = EarthImageryPacket{}
	mi := &file_streaming_imagery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthImageryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthImageryPacket) ProtoMessage() {}

func (x *EarthImageryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_imagery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthImageryPacket.ProtoReflect.Descriptor instead.
func (*EarthImageryPacket) Descriptor() ([]byte, []int) {
	return file_streaming_imagery_proto_rawDescGZIP(), []int{0}
}

func (x *EarthImageryPacket) GetImageType() EarthImageryPacket_Codec {
	if x != nil && x.ImageType != nil {
		return *x.ImageType
	}
	return Default_EarthImageryPacket_ImageType
}

func (x *EarthImageryPacket) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *EarthImageryPacket) GetAlphaType() EarthImageryPacket_SeparateAlphaType {
	if x != nil && x.AlphaType != nil {
		return *x.AlphaType
	}
	return Default_EarthImageryPacket_AlphaType
}

func (x *EarthImageryPacket) GetImageAlpha() []byte {
	if x != nil {
		return x.ImageAlpha
	}
	return nil
}

var File_streaming_imagery_proto protoreflect.FileDescriptor

var file_streaming_imagery_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x22, 0x82, 0x03, 0x0a, 0x12, 0x45, 0x61, 0x72, 0x74, 0x68,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x4a, 0x0a,
	0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x25, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e,
	0x45, 0x61, 0x72, 0x74, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x3a, 0x04, 0x4a, 0x50, 0x45, 0x47, 0x52, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x56, 0x0a, 0x0a, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x45, 0x61, 0x72, 0x74, 0x68,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x72, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x65,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x54, 0x79, 0x70, 0x65, 0x3a,
	0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x52, 0x09, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x6c, 0x70, 0x68,
	0x61, 0x22, 0x41, 0x0a, 0x05, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x50,
	0x45, 0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x50, 0x45, 0x47, 0x32, 0x30, 0x30, 0x30,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x58, 0x54, 0x31, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x58, 0x54, 0x35, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4e, 0x47, 0x5f, 0x52, 0x47,
	0x42, 0x41, 0x10, 0x04, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x65,
	0x41, 0x6c, 0x70, 0x68, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x4a, 0x50, 0x45, 0x47, 0x5f, 0x41, 0x4c, 0x50, 0x48, 0x41, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x52, 0x4c, 0x45, 0x5f, 0x31, 0x5f, 0x42, 0x49, 0x54, 0x10, 0x03, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x3b, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68,
})

var (
	file_streaming_imagery_proto_rawDescOnce sync.Once
	file_streaming_imagery_proto_rawDescData []byte
)

func file_streaming_imagery_proto_rawDescGZIP() []byte {
	file_streaming_imagery_proto_rawDescOnce.Do(func() {
		file_streaming_imagery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_imagery_proto_rawDesc), len(file_streaming_imagery_proto_rawDesc)))
	})
	return file_streaming_imagery_proto_rawDescData
}

var file_streaming_imagery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_streaming_imagery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streaming_imagery_proto_goTypes = []any{
	(EarthImageryPacket_Codec)(0),             // 0: GoogleEarth.EarthImageryPacket.Codec
	(EarthImageryPacket_SeparateAlphaType)(0), // 1: GoogleEarth.EarthImageryPacket.SeparateAlphaType
	(*EarthImageryPacket)(nil),                // 2: GoogleEarth.EarthImageryPacket
}
var file_streaming_imagery_proto_depIdxs = []int32{
	0, // 0: GoogleEarth.EarthImageryPacket.image_type:type_name -> GoogleEarth.EarthImageryPacket.Codec
	1, // 1: GoogleEarth.EarthImageryPacket.alpha_type:type_name -> GoogleEarth.EarthImageryPacket.SeparateAlphaType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streaming_imagery_proto_init() }
func file_streaming_imagery_proto_init() {
	if File_streaming_imagery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_imagery_proto_rawDesc), len(file_streaming_imagery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streaming_imagery_proto_goTypes,
		DependencyIndexes: file_streaming_imagery_proto_depIdxs,
		EnumInfos:         file_streaming_imagery_proto_enumTypes,
		MessageInfos:      file_streaming_imagery_proto_msgTypes,
	}.Build()
	File_streaming_imagery_proto = out.File
	file_streaming_imagery_proto_goTypes = nil
	file_streaming_imagery_proto_depIdxs = nil
}
