// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: terrain.proto

package GoogleEarth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TileType 瓦片类型枚举
type WaterSurfaceTileProto_TileType int32

const (
	WaterSurfaceTileProto_ALL_LAND  WaterSurfaceTileProto_TileType = 1 // 全部陆地
	WaterSurfaceTileProto_ALL_WATER WaterSurfaceTileProto_TileType = 2 // 全部水域
	WaterSurfaceTileProto_COAST     WaterSurfaceTileProto_TileType = 3 // 海岸线
)

// Enum value maps for WaterSurfaceTileProto_TileType.
var (
	WaterSurfaceTileProto_TileType_name = map[int32]string{
		1: "ALL_LAND",
		2: "ALL_WATER",
		3: "COAST",
	}
	WaterSurfaceTileProto_TileType_value = map[string]int32{
		"ALL_LAND":  1,
		"ALL_WATER": 2,
		"COAST":     3,
	}
)

func (x WaterSurfaceTileProto_TileType) Enum() *WaterSurfaceTileProto_TileType {
	p := new(WaterSurfaceTileProto_TileType)
	*p = x
	return p
}

func (x WaterSurfaceTileProto_TileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaterSurfaceTileProto_TileType) Descriptor() protoreflect.EnumDescriptor {
	return file_terrain_proto_enumTypes[0].Descriptor()
}

func (WaterSurfaceTileProto_TileType) Type() protoreflect.EnumType {
	return &file_terrain_proto_enumTypes[0]
}

func (x WaterSurfaceTileProto_TileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WaterSurfaceTileProto_TileType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WaterSurfaceTileProto_TileType(num)
	return nil
}

// Deprecated: Use WaterSurfaceTileProto_TileType.Descriptor instead.
func (WaterSurfaceTileProto_TileType) EnumDescriptor() ([]byte, []int) {
	return file_terrain_proto_rawDescGZIP(), []int{0, 0}
}

// WaterSurfaceTileProto 水面瓦片协议
type WaterSurfaceTileProto struct {
	state                     protoimpl.MessageState          `protogen:"open.v1"`
	TileType                  *WaterSurfaceTileProto_TileType `protobuf:"varint,1,opt,name=tile_type,json=tileType,enum=GoogleEarth.Terrain.WaterSurfaceTileProto_TileType,def=1" json:"tile_type,omitempty"` // 瓦片类型，默认为全部陆地
	Mesh                      []*WaterSurfaceTileProto_Mesh   `protobuf:"group,2,rep,name=Mesh,json=mesh" json:"mesh,omitempty"`
	TerrainVertexIsUnderwater []byte                          `protobuf:"bytes,13,opt,name=terrain_vertex_is_underwater,json=terrainVertexIsUnderwater" json:"terrain_vertex_is_underwater,omitempty"` // 地形顶点是否在水下
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for WaterSurfaceTileProto fields.
const (
	Default_WaterSurfaceTileProto_TileType = WaterSurfaceTileProto_ALL_LAND
)

func (x *WaterSurfaceTileProto) Reset() {
	*x = WaterSurfaceTileProto{}
	mi := &file_terrain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterSurfaceTileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterSurfaceTileProto) ProtoMessage() {}

func (x *WaterSurfaceTileProto) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterSurfaceTileProto.ProtoReflect.Descriptor instead.
func (*WaterSurfaceTileProto) Descriptor() ([]byte, []int) {
	return file_terrain_proto_rawDescGZIP(), []int{0}
}

func (x *WaterSurfaceTileProto) GetTileType() WaterSurfaceTileProto_TileType {
	if x != nil && x.TileType != nil {
		return *x.TileType
	}
	return Default_WaterSurfaceTileProto_TileType
}

func (x *WaterSurfaceTileProto) GetMesh() []*WaterSurfaceTileProto_Mesh {
	if x != nil {
		return x.Mesh
	}
	return nil
}

func (x *WaterSurfaceTileProto) GetTerrainVertexIsUnderwater() []byte {
	if x != nil {
		return x.TerrainVertexIsUnderwater
	}
	return nil
}

// TerrainPacketExtraDataProto 地形数据包额外数据协议
type TerrainPacketExtraDataProto struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	WaterTileQuads        []*WaterSurfaceTileProto `protobuf:"bytes,1,rep,name=water_tile_quads,json=waterTileQuads" json:"water_tile_quads,omitempty"`                        // 水面瓦片四边形列表
	OriginalTerrainPacket []byte                   `protobuf:"bytes,100,opt,name=original_terrain_packet,json=originalTerrainPacket" json:"original_terrain_packet,omitempty"` // 原始地形数据包
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TerrainPacketExtraDataProto) Reset() {
	*x = TerrainPacketExtraDataProto{}
	mi := &file_terrain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerrainPacketExtraDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerrainPacketExtraDataProto) ProtoMessage() {}

func (x *TerrainPacketExtraDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerrainPacketExtraDataProto.ProtoReflect.Descriptor instead.
func (*TerrainPacketExtraDataProto) Descriptor() ([]byte, []int) {
	return file_terrain_proto_rawDescGZIP(), []int{1}
}

func (x *TerrainPacketExtraDataProto) GetWaterTileQuads() []*WaterSurfaceTileProto {
	if x != nil {
		return x.WaterTileQuads
	}
	return nil
}

func (x *TerrainPacketExtraDataProto) GetOriginalTerrainPacket() []byte {
	if x != nil {
		return x.OriginalTerrainPacket
	}
	return nil
}

// Mesh 网格组
type WaterSurfaceTileProto_Mesh struct {
	state                protoimpl.MessageState                             `protogen:"open.v1"`
	AltitudeCm           *int32                                             `protobuf:"zigzag32,3,opt,name=altitude_cm,json=altitudeCm" json:"altitude_cm,omitempty"`                 // 高度（厘米）
	X                    []byte                                             `protobuf:"bytes,4,opt,name=x" json:"x,omitempty"`                                                        // X坐标数据
	Y                    []byte                                             `protobuf:"bytes,5,opt,name=y" json:"y,omitempty"`                                                        // Y坐标数据
	Alpha                []byte                                             `protobuf:"bytes,6,opt,name=alpha" json:"alpha,omitempty"`                                                // Alpha通道数据
	TriangleVertices     []int32                                            `protobuf:"varint,7,rep,name=triangle_vertices,json=triangleVertices" json:"triangle_vertices,omitempty"` // 三角形顶点列表
	Strips               []*WaterSurfaceTileProto_Mesh_Strips               `protobuf:"group,8,rep,name=Strips,json=strips" json:"strips,omitempty"`
	Additionaledgepoints []*WaterSurfaceTileProto_Mesh_AdditionalEdgePoints `protobuf:"group,10,rep,name=AdditionalEdgePoints,json=additionaledgepoints" json:"additionaledgepoints,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WaterSurfaceTileProto_Mesh) Reset() {
	*x = WaterSurfaceTileProto_Mesh{}
	mi := &file_terrain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterSurfaceTileProto_Mesh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterSurfaceTileProto_Mesh) ProtoMessage() {}

func (x *WaterSurfaceTileProto_Mesh) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterSurfaceTileProto_Mesh.ProtoReflect.Descriptor instead.
func (*WaterSurfaceTileProto_Mesh) Descriptor() ([]byte, []int) {
	return file_terrain_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WaterSurfaceTileProto_Mesh) GetAltitudeCm() int32 {
	if x != nil && x.AltitudeCm != nil {
		return *x.AltitudeCm
	}
	return 0
}

func (x *WaterSurfaceTileProto_Mesh) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *WaterSurfaceTileProto_Mesh) GetY() []byte {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *WaterSurfaceTileProto_Mesh) GetAlpha() []byte {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *WaterSurfaceTileProto_Mesh) GetTriangleVertices() []int32 {
	if x != nil {
		return x.TriangleVertices
	}
	return nil
}

func (x *WaterSurfaceTileProto_Mesh) GetStrips() []*WaterSurfaceTileProto_Mesh_Strips {
	if x != nil {
		return x.Strips
	}
	return nil
}

func (x *WaterSurfaceTileProto_Mesh) GetAdditionaledgepoints() []*WaterSurfaceTileProto_Mesh_AdditionalEdgePoints {
	if x != nil {
		return x.Additionaledgepoints
	}
	return nil
}

// Strips 条带组
type WaterSurfaceTileProto_Mesh_Strips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vertices      []int32                `protobuf:"varint,9,rep,name=vertices" json:"vertices,omitempty"` // 顶点列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterSurfaceTileProto_Mesh_Strips) Reset() {
	*x = WaterSurfaceTileProto_Mesh_Strips{}
	mi := &file_terrain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterSurfaceTileProto_Mesh_Strips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterSurfaceTileProto_Mesh_Strips) ProtoMessage() {}

func (x *WaterSurfaceTileProto_Mesh_Strips) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterSurfaceTileProto_Mesh_Strips.ProtoReflect.Descriptor instead.
func (*WaterSurfaceTileProto_Mesh_Strips) Descriptor() ([]byte, []int) {
	return file_terrain_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *WaterSurfaceTileProto_Mesh_Strips) GetVertices() []int32 {
	if x != nil {
		return x.Vertices
	}
	return nil
}

// AdditionalEdgePoints 额外边缘点组
type WaterSurfaceTileProto_Mesh_AdditionalEdgePoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    []byte                 `protobuf:"bytes,11,opt,name=coordinate" json:"coordinate,omitempty"` // 坐标数据
	Alpha         []byte                 `protobuf:"bytes,12,opt,name=alpha" json:"alpha,omitempty"`           // Alpha通道数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) Reset() {
	*x = WaterSurfaceTileProto_Mesh_AdditionalEdgePoints{}
	mi := &file_terrain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) ProtoMessage() {}

func (x *WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterSurfaceTileProto_Mesh_AdditionalEdgePoints.ProtoReflect.Descriptor instead.
func (*WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) Descriptor() ([]byte, []int) {
	return file_terrain_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) GetCoordinate() []byte {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *WaterSurfaceTileProto_Mesh_AdditionalEdgePoints) GetAlpha() []byte {
	if x != nil {
		return x.Alpha
	}
	return nil
}

var File_terrain_proto protoreflect.FileDescriptor

var file_terrain_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x54, 0x65, 0x72,
	0x72, 0x61, 0x69, 0x6e, 0x22, 0xf4, 0x05, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x65, 0x72, 0x53, 0x75,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5a,
	0x0a, 0x09, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x33, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e,
	0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x61, 0x74, 0x65, 0x72, 0x53, 0x75, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x08, 0x41, 0x4c, 0x4c, 0x5f, 0x4c, 0x41, 0x4e, 0x44,
	0x52, 0x08, 0x74, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x6d, 0x65,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x2f, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x57,
	0x61, 0x74, 0x65, 0x72, 0x53, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x68, 0x52, 0x04, 0x6d, 0x65, 0x73, 0x68, 0x12,
	0x3f, 0x0a, 0x1c, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x5f, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x77, 0x61, 0x74, 0x65, 0x72, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x19, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x56, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x49, 0x73, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x1a, 0xc4, 0x03, 0x0a, 0x04, 0x4d, 0x65, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0a,
	0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x43, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x12, 0x2b, 0x0a, 0x11,
	0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c,
	0x65, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x12, 0x4e, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x69, 0x70, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x36, 0x2e, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e,
	0x57, 0x61, 0x74, 0x65, 0x72, 0x53, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x69, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x70,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x73, 0x12, 0x78, 0x0a, 0x14, 0x61, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x44, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x45, 0x61, 0x72, 0x74, 0x68, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x61,
	0x74, 0x65, 0x72, 0x53, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x68, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x45, 0x64, 0x67, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x14, 0x61,
	0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x1a, 0x24, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x70, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x4c, 0x0a, 0x14, 0x41, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x64, 0x67, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x22, 0x32, 0x0a, 0x08, 0x54, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4c, 0x4c, 0x5f, 0x4c, 0x41, 0x4e, 0x44, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4c, 0x4c, 0x5f, 0x57, 0x41, 0x54, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x41, 0x53, 0x54, 0x10, 0x03, 0x22, 0xab, 0x01, 0x0a, 0x1b,
	0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x54, 0x0a, 0x10, 0x77,
	0x61, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x71, 0x75, 0x61, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61,
	0x72, 0x74, 0x68, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x61, 0x74, 0x65,
	0x72, 0x53, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x0e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6c, 0x65, 0x51, 0x75, 0x61, 0x64,
	0x73, 0x12, 0x36, 0x0a, 0x17, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x65,
	0x72, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x15, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x72, 0x72,
	0x61, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68,
})

var (
	file_terrain_proto_rawDescOnce sync.Once
	file_terrain_proto_rawDescData []byte
)

func file_terrain_proto_rawDescGZIP() []byte {
	file_terrain_proto_rawDescOnce.Do(func() {
		file_terrain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terrain_proto_rawDesc), len(file_terrain_proto_rawDesc)))
	})
	return file_terrain_proto_rawDescData
}

var file_terrain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_terrain_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_terrain_proto_goTypes = []any{
	(WaterSurfaceTileProto_TileType)(0),                     // 0: GoogleEarth.Terrain.WaterSurfaceTileProto.TileType
	(*WaterSurfaceTileProto)(nil),                           // 1: GoogleEarth.Terrain.WaterSurfaceTileProto
	(*TerrainPacketExtraDataProto)(nil),                     // 2: GoogleEarth.Terrain.TerrainPacketExtraDataProto
	(*WaterSurfaceTileProto_Mesh)(nil),                      // 3: GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh
	(*WaterSurfaceTileProto_Mesh_Strips)(nil),               // 4: GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh.Strips
	(*WaterSurfaceTileProto_Mesh_AdditionalEdgePoints)(nil), // 5: GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh.AdditionalEdgePoints
}
var file_terrain_proto_depIdxs = []int32{
	0, // 0: GoogleEarth.Terrain.WaterSurfaceTileProto.tile_type:type_name -> GoogleEarth.Terrain.WaterSurfaceTileProto.TileType
	3, // 1: GoogleEarth.Terrain.WaterSurfaceTileProto.mesh:type_name -> GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh
	1, // 2: GoogleEarth.Terrain.TerrainPacketExtraDataProto.water_tile_quads:type_name -> GoogleEarth.Terrain.WaterSurfaceTileProto
	4, // 3: GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh.strips:type_name -> GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh.Strips
	5, // 4: GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh.additionaledgepoints:type_name -> GoogleEarth.Terrain.WaterSurfaceTileProto.Mesh.AdditionalEdgePoints
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_terrain_proto_init() }
func file_terrain_proto_init() {
	if File_terrain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terrain_proto_rawDesc), len(file_terrain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terrain_proto_goTypes,
		DependencyIndexes: file_terrain_proto_depIdxs,
		EnumInfos:         file_terrain_proto_enumTypes,
		MessageInfos:      file_terrain_proto_msgTypes,
	}.Build()
	File_terrain_proto = out.File
	file_terrain_proto_goTypes = nil
	file_terrain_proto_depIdxs = nil
}
